### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by kiciek** [AtomLinter/linter-flake8#406] opened 2017-04-23 15:15 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

String was not closed somewhere inside the file. Flake8 couldn't tell line. It was NaN/NaN instead.

Debug information:
Atom version: 1.16.0
Flake8 version: `2.5.5 (pep8: 1.5.7, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1, pyflakes: 0.8.1) CPython 3.5.1+ on Linux`

**Comment by Arcanemagus** [comment] 2017-04-24 18:56
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-05-02 21:26
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-05-02 21:26 UTC
Labels: External
