### ISSUE TITLE
W291(tailing whitespace) broke linter if some block is folded

### ISSUE THREAD

**Issue by Holi0317** [AtomLinter/linter-flake8#109] opened 2015-11-11 09:30 UTC
Using the following snippet:
```python
class Main(object):
    DUMMY_STRING = '''
        spam
        spam
        spam
        spam
        spam
        spam
        spam
    '''

    def main():
        '''
        This is the docstring for main
        '''
        pass
```

Copy it to atom and fold `Main.DUMMY_STRING`.

Then add a space after docstring of main and create W291 warning.

linter-flake8 will create a TypeError: cannot read property of length of undefined on line 99:67

Perhaps this is a atom bug instead of linter-flake8 bug?

atom version: 1.1.0
linter version: 1.10.0
linter-flake8 version: 1.9.1
flake8 version: 2.5.0

**Comment by cbscribe** [comment] 2015-11-11 20:00
This seems like the same issue from #108

**Comment by Arcanemagus** [comment] 2015-11-11 22:02
Definitely a duplicate of #108, I've got some time now so I'll try looking into this. Marking as closed.

**Closed by Arcanemagus** 2015-11-11 22:02 UTC

**Comment by Arcanemagus** [comment] 2015-11-12 08:01
Thanks for your detailed steps to reproduce btw, made it simple to trigger this and verify the issue was solved.
