### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by Guy-Markman** [AtomLinter/linter-flake8#278] opened 2016-11-19 12:57 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`. at line1 col 1

#!/usr/bin/env python
import base
import constants

class CyclicBuffer(base.Base):

    def __init__(self, mm,):
        super(CyclicBuffer, self).__init__()
        self.mm = mm

    def get_head_offset(self):
        return self.mm[-2 * constants.OFFSET_SIZE:-1 * constants.OFFSET_SIZE]

    def set_head_offset(self, value):
        self.mm[-2 * constants.OFFSET_SIZE:-1 * constants.OFFSET_SIZE] = value

    def get_tail_offset(self):
        return self.mm[-1 * constants.OFFSET_SIZE:]

    def set_tail_offset(self, value):
        self.mm[-1 * constants.OFFSET_SIZE:] = value

    def read_head(self):
        head_offset = self.get_head_offset()
        ans = self.mm[head_offset]
        if head_offset + 1 <=
        constants.BUFFER_SIZE - 2 * constants.OFFSET_SIZE:
            self.set_head_offset(head_offset + 1)
        else:
            self.set_head_offset(0)
        return ans

    def read_tail(self):
        tail_offset = self.get_head_offset()
        ans = self.mm[tail_offset]
        if tail_offset + 1 <=
        constants.BUFFER_SIZE - 2 * constants.OFFSET_SIZE:
            self.set_tail_offset(tail_offset + 1)
        else:
            self.set_tail_offset(0)
        return ans

Debug information:
Atom version: 1.12.4
Flake8 version: `3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.12 on Windows`

**Comment by Arcanemagus** [comment] 2016-11-20 04:36
Please update your `flake8` and try again, v3.1.0 fixed one issue related to `E999` errors which it looks like you might be hitting here.

**Comment by Arcanemagus** [comment] 2016-11-30 17:10
Closing due to a lack of response, if you are still experiencing this after updating to `flake8>=3.2.1` please either file a new issue or respond here with code to reproduce it, thanks!

**Closed by Arcanemagus** 2016-11-30 17:10 UTC
Labels: External
