### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by SharpBit** [AtomLinter/linter-flake8#526] opened 2017-11-14 23:51 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: unexpected EOF while parsing`.

the first line is where the error is no matter what it is

Debug information:
Atom version: 1.22.0
Flake8 version: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.2 on Windows`

**Comment by Arcanemagus** [comment] 2017-12-04 19:52
Duplicate of #505

**Closed by Arcanemagus** 2017-12-04 19:52 UTC
Labels: duplicate
