### ISSUE TITLE
Ignore option does nothing

### ISSUE THREAD

**Issue by vasa-chi** [AtomLinter/linter-flake8#249] opened 2016-09-22 10:06 UTC
<img width="236" alt="2016-09-22 13 05 15" src="https://cloud.githubusercontent.com/assets/180167/18744151/49f6d4b2-80c5-11e6-8def-a672f41a4449.png">

It seems that this option currently does nothing. I still get ignored warnings and errors.

If I pass config options in setup.cfg - everything works
```
[flake8]
ignore = W291, W293
```

**Comment by Arcanemagus** [comment] 2016-10-15 06:33
I'm marking this as fixed in #255 as I can't reproduce it on that code base.

**Closed by Arcanemagus** 2016-10-15 06:33 UTC
