### ISSUE TITLE
LinterFlake8.Linter is deprecated.

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-flake8#51] opened 2015-07-08 18:53 UTC
More deprecation warnings

----

AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterFlake8.Linter (C:\Users\Landon\.atom\packages\linter\lib\linter.coffee:60:4)
new LinterFlake8 (C:\Users\Landon\.atom\packages\linter-flake8\lib\linter-flake8.coffee:25:4)
Object.lint (C:\Users\Landon\.atom\packages\linter\lib\legacy.coffee:61:21)
<unknown> (C:\Users\Landon\.atom\packages\linter\lib\editor-linter.coffee:68:23)
<unknown> (C:\Users\Landon\.atom\packages\linter\lib\editor-linter.coffee:67:24)
Set.forEach (native)
```

**Comment by alysivji** [comment] 2015-07-09 03:40
+1

**Comment by steelbrain** [comment] 2015-07-09 07:47
Dupe of #50

**Closed by steelbrain** 2015-07-09 07:47 UTC

**Comment by Arcanemagus** [comment] 2015-07-09 15:05
Not exactly, but the fix is the same :wink:.
