### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by taogasaw** [AtomLinter/linter-flake8#329] opened 2017-01-07 04:29 UTC
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

Debug information:
Atom version: 1.12.8
Flake8 version: `3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.12 on Darwin`

```py
# -*- coding: utf-8 -*-
```

**Comment by Arcanemagus** [comment] 2017-01-09 08:48
Can you provide code to replicate this with? This is a new message that I haven't seen before...

**Comment by Arcanemagus** [comment] 2017-02-16 18:19
If I had to guess, this is most likely a duplicate of [pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306), however without any more detailed example code to test with it is impossible to determine.

Closing for now, but if you think the above issue isn't relevant please post a code example to trigger this error!

**Closed by Arcanemagus** 2017-02-16 18:19 UTC
Labels: bug, External
