### ISSUE TITLE
Flake8 rule 'W292' reported an invalid point

### ISSUE THREAD

**Issue by kevhill** [AtomLinter/linter-flake8#418] opened 2017-04-26 20:24 UTC
Flake8 reported an invalid point for the rule `W292`, with the messge `no newline at end of file`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment] 2017-04-26 20:46
Do you have any unicode in the file? Are you able to share the raw file to try to reproduce this?

**Comment by Arcanemagus** [comment] 2017-05-03 17:42
Closing as I was unable to reproduce this and no example file has been provided.

As this is a `flake8` bug, it will need to be reported in the [`flake8` repository](https://gitlab.com/pycqa/flake8), if you want me to take care of that I'll need a file which lets me reproduce the issue.

**Closed by Arcanemagus** 2017-05-03 17:42 UTC
