### ISSUE TITLE
Flake8 crashed!

### ISSUE THREAD

**Issue by hover-cheng** [AtomLinter/linter-flake8#423] opened 2017-05-02 08:36 UTC
linter-flake8:: Flake8 threw an error related to: TypeError: unorderable types: str() > int() Please check Atom's Console for more details

**Comment by ibmboy19** [comment] 2017-05-02 09:56
I have the same problem.
![image](https://cloud.githubusercontent.com/assets/6712103/25613419/b5c18e04-2f60-11e7-8043-3b6972f59aaf.png)

**Comment by Arcanemagus** [comment] 2017-05-02 21:25
This message is only shown when `flake8` itself has crashed!

You can see the "most recent" message in the notification, but the full stack trace is only available in the console. You need to open Atom's Developer Tools to view that.

@ibmboy19 That's odd that it's not reading your locale correctly. What OS are you on?

**Comment by hover-cheng** [comment] 2017-05-03 03:01
main.js:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "c:\python3\lib\site-packages\flake8\checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "c:\python3\lib\site-packages\flake8\processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcae' in position 771: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\python3\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "c:\python3\lib\site-packages\flake8\main\application.py", line 316, in _run
    self.run_checks()
  File "c:\python3\lib\site-packages\flake8\main\application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 319, in run
    self.run_serial()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 303, in run_serial
    checker.run_checks()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "c:\python3\lib\site-packages\flake8\checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: unorderable types: str() > int()(anonymous function) @ main.js:201
main.js:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "c:\python3\lib\site-packages\flake8\checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "c:\python3\lib\site-packages\flake8\processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcae' in position 771: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\python3\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "c:\python3\lib\site-packages\flake8\main\application.py", line 316, in _run
    self.run_checks()
  File "c:\python3\lib\site-packages\flake8\main\application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 319, in run
    self.run_serial()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 303, in run_serial
    checker.run_checks()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "c:\python3\lib\site-packages\flake8\checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "c:\python3\lib\site-packages\flake8\checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: unorderable types: str() > int()(anonymous function) @ main.js:201step @ C:\Users\S1691\.atom\packages\linter-flake8\lib\main.js:9_tickCallback @ internal/process/next_tick.js:103

**Comment by ibmboy19** [comment] 2017-05-03 13:26
@Arcanemagus It's under windows.
I finally figure out the problem is the lack of some dependency.

**Comment by Arcanemagus** [comment] 2017-05-03 17:37
@hover-cheng Wow! That is one crazy stack trace, it looks like you have a `\udcae` character in your code that is causing `flake8` to crash.

Are you able to share the code in question? This needs to be reported in the [`flake8` repository](https://gitlab.com/pycqa/flake8).

**Comment by hover-cheng** [comment] 2017-05-04 02:45
@Arcanemagus thank you,because the use of Chinese,so that is causing flake8 to crash.

**Comment by Arcanemagus** [comment] 2017-05-04 16:25
@hover-cheng Does `flake8` work in the CLI for you?

**Comment by Arcanemagus** [comment] 2017-05-08 16:44
Closing due to this being an issue with `flake8` and/or system configuration.

**Closed by Arcanemagus** 2017-05-08 16:44 UTC
Labels: External

**Comment by guillochon** [comment] 2017-05-13 15:16
I'm getting this same error with flake8 3.3. The above poster's "lack of some dependency" is not particularly helpful...

**Comment by Arcanemagus** [comment] 2017-05-14 00:09
@guillochon Did you check the console for the detailed information...?

**Comment by guillochon** [comment] 2017-05-14 02:33
@Arcanemagus I'm actually not sure how to do that...the key stroke listed on the web to enable the dev tools don't seem to do anything: https://discuss.atom.io/t/how-to-make-developer-tools-appear/16232

**Comment by luboss** [comment] 2017-05-15 16:10
I have similar issue:
_`UnicodeEncodeError: 'utf-8' codec can't encode character '\udc8d' in position 1344: surrogates not allowed`_

I found out that the file is encoded in UTF-8 with Byte Order Mark. When I convert it to pure UTF-8 the issue disappears.

**Comment by Arcanemagus** [comment] 2017-05-15 16:27
@luboss There is a known bug with the current version of `flake8` that is fixed in their `master` but still waiting on release.

@guillochon <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> is the Windows (and Linux?) keyboard shortcut, you can always go to View -> Developer -> Toggle Developer Tools though.

**Comment by carldunham** [comment] 2017-09-12 11:00
#451 has more useful information, for people like me who arrive here looking

**Comment by Mi-lex** [comment] 2017-11-17 10:01
I have the problem which look similar and it's not unreadable character, because it crashes even before I type smth.

![python issue](https://user-images.githubusercontent.com/30773104/32941576-3fb74c48-cb97-11e7-8b12-2c544195ab7d.png)

**Comment by eablonet** [comment] 2018-06-13 21:34
Hi,

I had a similar problem.
In my case it seems to come from a conflict between linter-flake8 and linter-spell.
Disable linter-spell solved the problem.
