### ISSUE TITLE
flake8 not found

### ISSUE THREAD

**Issue by screendriver** [AtomLinter/linter-flake8#18] opened 2015-03-01 13:32 UTC
flake8 is installed via my package manager (pacman) and is in my path
```bash
me@there ~/ % which flake8                                           
/usr/bin/flake8
```
But linter-flake8 tells me
```
Failed to spawn command /usr/bin/flake8. Make sure /usr/bin/flake8 is installed and on your PATH
```
I already set the executable Directory in ```~/.atom/config.cson```. Atom tells me
```javascript
/usr/share/atom/resources/app/src/buffered-process.js:104 Uncaught BufferedProcessError: Failed to spawn command `/usr/bin/flake8`. Make sure `/usr/bin/flake8` is installed and on your PATH
```

**Comment by max-orhai** [comment] 2015-03-03 21:27
I'm experiencing the same bad behavior, using Mac OS X 10.9.5.

**Comment by badray** [comment] 2015-03-10 09:35
@ScreenDriver @max-orhai Are you still experiencing issue? Have you tried reopening Atom? 

> Worse, I have to disable the entire linter package to stop the error messages; disabling linter-flake8 has no effect.

Sounds like new(old) issue. Plugin miss deinitialization.

**Comment by ScreenDriver** [comment] 2015-03-11 07:25
I don't know. I didn't use Atom + Python recently. I will try it as soon as possible.

**Comment by sadovnychyi** [comment] 2015-03-11 14:19
Same here for me.

**Comment by max-orhai** [comment] 2015-03-11 16:24
@badray Yes, I've tried restarting. Other linters (jshint etc) work fine.

I assume that since you're the package owner and you haven't updated recently, it's working for you. Are you using the most recent Atom? What OS are you using?

**Comment by badray** [comment] 2015-03-11 19:56
@max-orhai Yes the most recent Atom version on my mbp and pc. Linter works for me on OSX 10.10.2, and Ubuntu 14.04. Some Windows guy was reporting it works for him too. And to be clear, I was updating package recently(recently for me).

Please @max-orhai @ScreenDriver @sadovnychyi type into terminal `$> which flake8`, then `$> sh` then `$> echo $PATH` in that order.

**Comment by max-orhai** [comment] 2015-03-11 20:29
@badray Atom says "All of your installed packages are up to date!" but I still have the same issue.
flake8 is in my `sh` path, as you can see: 
```
maxintosh:~ max$ which flake8
/usr/local/bin/flake8
maxintosh:~ max$ sh
sh-3.2$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/texbin:anaconda/bin:/Users/max/sys-utils/bin
```
I can run flake8 from the command line without any problem.

**Comment by badray** [comment] 2015-03-11 20:43
@max-orhai ok :), I think we are close to it. How looks like your Atom init script? To open it, select from menu `Atom->Open Your Init Script`

Does it looks like this?
```
process.env.PATH = ['/usr/local/bin/', process.env.PATH].join(':')
```
Please post yor init file, or just tell if adding '/usr/local/bin' to nodejs paths did the trick.

**Comment by max-orhai** [comment] 2015-03-11 21:35
@badray My init script didn't amend my node path, and indeed my `process.env.PATH` didn't include /usr/local/bin when I checked from the dev tools command line.

Rather than adding that line to my init script (which runs every time Atom opens a window) I added `'executableDir': '/usr/local/bin'` to linter-flake8's config in ~/.atom.config.cson, as the package settings documentation suggests. I must have missed that earlier!

That stopped the error messages, but linter-flake8 still doesn't seem to be functional; it doesn't display any PEP8 notifications as I was expecting, even after restarting Atom (version 0.187.0 now). The `linter-jshint` package works fine, so I don't think it's a problem with `linter`.

**Comment by badray** [comment] 2015-03-12 09:23
@max-orhai yes init script is not the best place for doing this as env.PATH will grow and grow :). Docs that are included says clearly that `Atom will evaluate this file(*init script*) each time a new window is opened` . That was the simplest(temporary!) way of adding it to path, that was in my mind rather than explaining other ways - btw. I was quite sure that you've already tried configuring `linter-flake8` config in `~/.atom.config.cson` and there is some bug so... :).

If you read the code of the linter - it is more like config than code! - you will see that it doesn't differ much with `linter-jshint`. Maybe that `cmd` in `linter-flake8` is string not array, but according to `AtomLinters` code it is fine.

Are you sure that your `flake8` works properly? Maybe try to disable some other plugins? And some stupid question... Did you close atom with `cmd-q`?

If not, I'm out of ideas. So if you want to use this linter plugin, could you try to debug it? That would give us more precise data about whats going on?

**Comment by max-orhai** [comment] 2015-03-13 17:07
OK, I'll try to debug this when I have some time. I verified that flake8 does work on the command line for me. Anyway, my original issue seems to be solved now.

**Comment by ScreenDriver** [comment] 2015-04-08 13:46
I still have the issue. Nothing changed here. Please reopen the issue. Thank you.

**Comment by badray** [comment] 2015-04-08 14:33
@ScreenDriver Ok, sorry I just didn't receive any feedback from you after my suggestions what to do. So I assumed that this solved your problem and you forgot to reply...

**Comment by ScreenDriver** [comment] 2015-04-08 15:37
:+1: :wink:

**Comment by sh4nks** [comment] 2015-04-10 07:29
I had the same issue, but adding this fixed it (got this from your comment above): 
    process.env.PATH = ['/usr/local/bin/', process.env.PATH].join(':')

I am running OSX 10.10.3

**Comment by Traviskn** [comment] 2015-04-13 17:13
@sh4nks I had the same issue as well, but was able to fix it with the same approach you used.

**Comment by muppetjones** [comment] 2015-05-22 17:19
I just updated to this package, and I'm getting the same error now. I did not change anything except update to the latest package. The path is still correct, and the flake8 binary is still there. The above suggestions do not work.

Can you please reopen this?

**Comment by hodgesmr** [comment] 2015-06-22 16:36
I also had the issue where it was looking for `flake8` inside a virtualenv. On OS X, I resolved this by setting the Binary Name to `/usr/local/bin/flake8`

**Comment by badray** [comment] 2015-06-24 08:42
@muppetjones happy to hear that you fixed it.

**Comment by mcandre** [comment] 2015-07-21 18:58
> On OS X, I resolved this by setting the Binary Name to /usr/local/bin/flake8 (after making sure it was installed globally)

@hodgesmr Works on my machine!

> Worse, I have to disable the entire linter package to stop the error messages; disabling linter-flake8 has no effect.

This bug still happens on my machine. Atom 1.0.2 / Mac OS X 10.10.4 Yosemite.

**Comment by badray** [comment] 2015-08-07 09:02
@ScreenDriver could you try soluton from https://github.com/AtomLinter/linter-flake8/issues/60#issuecomment-127640735 and tell if it fixed your issue?

**Comment by dtherrick** [comment] 2015-08-11 14:22
it's back again.

OS: OS X 10.10.4
Atom: 1.0.5
linter/flake8: 1.6.0

I updated to 1.6.0 yesterday and at that point the linter stopped working. On save, get: 
"Failed to spawn command flake8. Make sure flake8 is installed and on your PATH"

Verified that flake8 is installed and in the expected location (/usr/local/bin/flake8)

Ran into this bug on an earlier release, and adding the path (/usr/local/bin/flake8) to the Config File Name resolved it for me. This now fails.

Tried solution from #60 above, does not solve the problem for me.

**Comment by badray** [comment] 2015-08-11 14:51
Please paste your Executable Path setting screenshoot?

Wysłane z iPhone'a

Dnia 11 sie 2015 o godz. 16:22 Damian Herrick <notifications@github.com> napisał(a):

**Comment by dtherrick** [comment] 2015-08-11 14:56
sure - glad to. I know I'm using Config File Names and not Executable Path - but when using different variants (put the path in the Executable, the filename in Config File Name) it breaks. Using the settings as it is here worked before. Really appreciate the fast feedback though!

Also, have restarted Atom after each time I make any settings change.

<img width="755" alt="screenshot 2015-08-11 10 54 24" src="https://cloud.githubusercontent.com/assets/537765/9200815/a1ea51fc-4017-11e5-911b-9e89304ad1b1.png">

**Comment by dtherrick** [comment] 2015-08-11 15:19
Fixed it - moving the /usr/local/bin/flake8 to the Executable Path seems to get it right now.
Thanks again for the attention!

**Comment by Arcanemagus** [comment] 2015-08-11 17:06
LintOnFly being disabled is already documented here: https://github.com/AtomLinter/linter-flake8/issues/61, it looks like somebody just needs to submit a PR for it :wink:.

**Comment by badray** [comment] 2015-08-12 08:09
@dtherrick Please do not use Config File Names to point `flake8` executable :).  Lint on the fly will be enabled by default in 1.6.1.

**Comment by fxstein** [comment] 2015-08-24 18:26
Same issue here. Tried with and without executeable path /usr/local/bin/flake8

OSX 10.10.5
Atom 1.0.7
linter 1.4.3
linter-flake8 1.6.1
flake8 2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 2.7.10 on Darwin

Always get error

    Uncaught BufferedProcessError: Failed to spawn command `flake8
    /usr/local/bin/flake8`. Make sure `flake8
    /usr/local/bin/flake8` is installed and on your PATH

**Comment by fxstein** [comment] 2015-08-24 19:06
Cleaning up the config settings fixed mine. Using Copy/Paste from terminal added an extra \n into the setting and caused both errors. 

Mine is working now.

**Comment by chrisjlebron** [comment] 2015-09-02 19:26
Confirmed: adding the path to the "Executable Path" setting makes linter work as expected.

For those interested in my issue, I previously had the path `/usr/local/bin/` in the setting for "Executable Dir", but after a recent update this linter broke. As prompted by other posters here (thanks @dtherrick), I added the path to the other setting, and everything worked again.

From the screenshot above (and the code at https://github.com/AtomLinter/linter-flake8/blob/master/lib/main.coffee), it appears that "Executable Dir" was removed from the config settings. So yeah, that would make sense.

In case anyone else had my issue...

**Comment by jim-12gigs** [comment] 2015-09-28 15:19
The shebang line in the flake8 file might point to an older version of python. We have python 3.5 installed, but the shebang line points to version 3.4. Changing it to point to the installed python corrects the errors in atom.

#!/usr/local/opt/python3/bin/python3.5

**Comment by Arcanemagus** [comment] 2015-10-08 16:07
Marking this as closed as at this point the issues would either be using OS X and not running from the command line (or workarounds for this), improperly specified paths, or potentially a different `python` installed than `flake8` is expecting (which is an upstream issue).

**Closed by Arcanemagus** 2015-10-08 16:07 UTC
Labels: bug

**Comment by thevaliantx** [comment] 2016-01-11 04:29
I just resolved this on Ubuntu 15.04 by entering "sudo apt-get install python-flake8" into the terminal.  All is well now :)

**Comment by Cole128** [comment] 2017-05-19 20:49
I had this problem, except I couldn't find flake8 in my `/usr/bin` When you install packages from pip that also install command line tools, you must use sudo -H. Uninstall flake8, and then install it again: `sudo -H pip install flake8` . Use `pip3` for python3.

**Comment by SebastianOpiyo** [comment] 2017-12-01 18:55
thanks @Cole128 . that was a quick fix for me.

**Comment by Cole128** [comment] 2017-12-01 18:56
Thanks @SebastianOpiyo . Using sudo is probably a bad idea for most things, but it works for this.

**Comment by BullFranko** [comment] 2019-05-20 20:48
Well, I used to have the same problem, and my current OS is MacOS 10.12.6 .

I solve it just by installing flake8.
Just run this in your terminal:

$  python3 -m pip install flake8

That's it. 

Greetings.
