### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by AdamHe17** [AtomLinter/linter-flake8#319] opened 2016-12-20 04:14 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `IndentationError: expected an indented block`.

Debug information:
Atom version: 1.12.7
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 0.8.1, flake8-docstrings: 0.2.6, pep257: 0.7.0, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1) CPython 2.7.11 on Windows`

**Comment by Arcanemagus** [comment] 2016-12-21 22:06
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

Note that `hacking` is _very_ out of date and requires an ancient version of `flake8`. If you _need_ it then you are unfortunately stuck on that unsupported version and will simply have to ignore these invalid point messages.

**Comment by Arcanemagus** [comment] 2016-12-27 17:04
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-27 17:04 UTC
Labels: External
