### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by mmaja** [AtomLinter/linter-flake8#538] opened 2017-11-30 09:46 UTC
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

Debug information:
Atom version: 1.12.4
Flake8 version: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.14 on Darwin`

**Comment by Arcanemagus** [comment] 2017-12-04 19:57
Duplicate of #493

**Closed by Arcanemagus** 2017-12-04 19:57 UTC
