### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Yvee1** [AtomLinter/linter-flake8#487] opened 2017-08-10 19:40 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (80 > 79 characters)`.

```python
"""Exercise 05 List Overlap.

Take two lists, say for example these two:
  a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
  b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
and write a program that returns a list that contains only the elements that
are common between the lists (without duplicates). Make sure your program works
on two lists of different sizes.

Extras:

- Randomly generate two lists to test this
- Write this in one line of Python (don’t worry if you can’t figure this out
at this point - we’ll get to it soon)
"""
```

Debug information:
Atom version: 1.19.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`

**Comment by Yvee1** [comment] 2017-08-10 19:42
Again... With similar exercises it worked just fine.

**Comment by Arcanemagus** [comment] 2017-08-29 18:10
Duplicate of #486

**Comment by Arcanemagus** [comment] 2017-08-29 18:10
Same as in your previous issue, it's the `’` that is breaking `flake8`.

**Closed by Arcanemagus** 2017-08-29 18:10 UTC
