### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by KoushiHarada** [AtomLinter/linter-flake8#330] opened 2017-01-09 07:04 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.9
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.2.1, pyflakes: 1.1.0) CPython 3.5.2 on Linux`

**Comment by Arcanemagus** [comment] 2017-01-09 08:49
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-01-12 19:27
Closing as a duplicate of #331 as you posted a screenshot there.... the problem is still an outdated `flake8` version though.

**Closed by Arcanemagus** 2017-01-12 19:27 UTC
Labels: duplicate, External
