### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by Gamdel** [AtomLinter/linter-flake8#490] opened 2017-08-21 07:41 UTC
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

Debug information:
Atom version: 1.18.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment] 2017-12-04 19:54
Duplicate of #466

**Closed by Arcanemagus** 2017-12-04 19:54 UTC
