### ISSUE TITLE
TypeError: item.replace is not a function

### ISSUE THREAD

**Issue by Jyree** [AtomLinter/linter-flake8#203] opened 2016-06-13 18:37 UTC
Catch this error. When i'm trying to write something comes more errors 
![image](https://cloud.githubusercontent.com/assets/8149366/16018826/e0bc9c3a-31ae-11e6-8375-c5f7f97d2640.png)

Windows 10, python3(Anaconda)

**Comment by Arcanemagus** [comment] 2016-06-13 18:46
What version of Atom are you on? It sounds like you need to update your version.

**Comment by Jyree** [comment] 2016-06-13 18:49
Just deleted atom and installed again.
Also reinstalled linter-flake8 through apm.
Have the same troubles
![image](https://cloud.githubusercontent.com/assets/8149366/16019242/9c846b4a-31b0-11e6-9988-68e5789f7332.png)

**Comment by Arcanemagus** [comment] 2016-06-13 18:52
@steelbrain it looks like Atom isn't liking [this line](https://github.com/steelbrain/exec/blob/v2.0.3/src/helpers.js#L81) for some reason, any ideas?

**Comment by steelbrain** [comment] 2016-06-13 18:53
Then it seems like one of the process parameter is non-stringish

**Comment by Jyree** [comment] 2016-06-13 19:00
https://gist.github.com/Jyree/b2d2643116ac32a3403816eba9ebd447
last error is about this file

**Comment by steelbrain** [comment] 2016-06-13 19:01
@Jyree the problem is not in that file but the one using it's API. One of them is giving invalid parameters. We do validate the parameter to be array but we do not validate each of it's entries to be stringish

**Comment by Arcanemagus** [comment] 2016-06-13 19:02
Looks like it doesn't like the `-1` which is the default value for `maxComplexity`, as this works perfectly fine for the `BufferedProcess` version this is something that should be fixed in `exec`.

**Comment by Arcanemagus** [comment] 2016-06-13 19:02
![image](https://cloud.githubusercontent.com/assets/427137/16019629/bba58d26-315e-11e6-9f30-354c018ab8ab.png)

I'll file an issue over there.

**Comment by steelbrain** [comment] 2016-06-13 19:03
I suppose we can coerce them to string, opening a PR in sb-exec

**Comment by Jyree** [comment] 2016-06-13 19:13
I'm not a js coder so if you want something from me describe the task in details, please

**Comment by Arcanemagus** [comment] 2016-06-13 19:15
@Jyree We've tracked down the error and @steelbrain is working on a fix, you can follow https://github.com/steelbrain/exec/issues/27 for updates.

**Comment by steelbrain** [comment] 2016-06-13 19:25
sb-exec release is out with the fix, bumping it in atom-linter now

**Comment by steelbrain** [comment] 2016-06-13 19:29
`atom-linter` v5.0.2 is out

**Comment by Arcanemagus** [comment] 2016-06-13 19:32
@Jyree if you uninstall and re-install `linter-flake8` it should be fixed for you.

**Comment by Jyree** [comment] 2016-06-13 19:47
Works, thanks

**Closed** 2016-06-13 20:15 UTC
Labels: bug, External
