### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by diogosfs** [AtomLinter/linter-flake8#115] opened 2015-11-25 07:01 UTC
```
Error: Traceback (most recent call last): File "c:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main "main", mod_spec) File "c:\anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Anaconda3\Scripts\flake8.exe__main.py", line 9, in File "c:\anaconda3\lib\site-packages\flake8\main.py", line 33, in main report = flake8_style.check_files() File "c:\anaconda3\lib\site-packages\flake8\engine.py", line 176, in check_files return self._retry_serial(self._styleguide.check_files, paths=paths) File "c:\anaconda3\lib\site-packages\flake8\engine.py", line 167, in _retry_serial return func(args, *kwargs) File "c:\anaconda3\lib\site-packages\pep8.py", line 1672, in check_files runner(path) File "c:\anaconda3\lib\site-packages\flake8\engine.py", line 121, in input_file return fchecker.check_all(expected=expected, line_offset=line_offset) File "c:\anaconda3\lib\site-packages\pep8.py", line 1412, in check_all self.check_ast() File "c:\anaconda3\lib\site-packages\pep8.py", line 1358, in check_ast checker = cls(tree, self.filename) File "c:\anaconda3\lib\site-packages\flake8_docstrings.py", line 27, in init__ self.source = self.load_source() File "c:\anaconda3\lib\site-packages\flake8_docstrings.py", line 43, in load_source self.source = pep8.stdin_get_value() File "c:\anaconda3\lib\site-packages\pep8.py", line 1060, in stdin_get_value return TextIOWrapper(sys.stdin.buffer, errors='ignore').read() ValueError: I/O operation on closed file
Error: Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\flake8\main.py", line 33, in main
    report = flake8_style.check_files()
  File "c:\anaconda3\lib\site-packages\flake8\engine.py", line 176, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "c:\anaconda3\lib\site-packages\flake8\engine.py", line 167, in _retry_serial
    return func(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\pep8.py", line 1672, in check_files
    runner(path)
  File "c:\anaconda3\lib\site-packages\flake8\engine.py", line 121, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "c:\anaconda3\lib\site-packages\pep8.py", line 1412, in check_all
    self.check_ast()
  File "c:\anaconda3\lib\site-packages\pep8.py", line 1358, in check_ast
    checker = cls(tree, self.filename)
  File "c:\anaconda3\lib\site-packages\flake8_docstrings.py", line 27, in __init__
    self.source = self.load_source()
  File "c:\anaconda3\lib\site-packages\flake8_docstrings.py", line 43, in load_source
    self.source = pep8.stdin_get_value()
  File "c:\anaconda3\lib\site-packages\pep8.py", line 1060, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file
    at exit (file:///C:/Users/diogo/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.coffee:33:24)
    at triggerExitCallback (C:\Users\diogo\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\diogo\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment] 2015-11-25 19:56
Duplicate of #103, try using `flake8-docstrings` instead of `flake8-pep257`.

**Closed by Arcanemagus** 2015-11-25 19:56 UTC
