### ISSUE TITLE
Error: Process execution timed out

### ISSUE THREAD

**Issue by jjlorenzo** [AtomLinter/linter-flake8#169] opened 2016-03-07 19:17 UTC
```
Error: Process execution timed out
    at /Users/jjlorenzo/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.js:79:18
```
After reinstalling linter-flake8, #168 was fixed, but now appears this.

OSX 10.11.3
Atom 1.6.0-beta7

**Comment by Arcanemagus** [comment] 2016-03-07 19:20
You should only be hitting this if `flake8` is taking longer than 10 seconds to run :open_mouth:

Does `flake8` take that long from the Terminal?

**Comment by jjlorenzo** [comment] 2016-03-08 02:10
No it doesn't, it runs fast, its rare, I mean it is not as frequent as my
previous reported issue.

I really don't think that in a ruby project I had to face this problems
when this doesn't happen in a python one, I do both.

Thanks
​

**Comment by Arcanemagus** [comment] 2016-03-08 17:53
I'm adding an option that disables throwing the error, most likely what is going on is a process is getting stuck (for whatever reason), everything else moves on, and then after a bit it's getting killed and throwing this... which we don't really care about.

**Comment by jjlorenzo** [comment] 2016-03-08 18:39
Thanks!
​

**Comment by ryanisnan** [comment] 2016-03-24 22:09
I'm also having this issue, when flake8 runs fine from terminal.

I've also noticed that this is an issue with https://github.com/AtomLinter/linter-phpcs/ and https://github.com/AtomLinter/linter-csslint/.

All three of these projects seem to have the issue in the same file (.atom\packages\<specific_atom_linter_here>\node_modules\atom-linter\lib\helpers.js:79:18).

**Comment by v3ss0n** [comment] 2016-03-28 13:26
I am having this issue , anytime it lints python file. Flake8 runs perfectly fine in other use cases.

**Comment by v3ss0n** [comment] 2016-03-28 13:35
Also it fails to do any code analysis.

**Comment by ryanisnan** [comment] 2016-04-06 18:20
@Arcanemagus is there any way the AtomLinter team can look into this, given that it's happening in multiple linters?

**Comment by Arcanemagus** [comment] 2016-04-06 18:26
@ryanisnan I'm _actually_ working on the PR I was talking about earlier, sorry about the delay.

For most linters this isn't an issue, for a few that need to legitimately run for that long an option should be provided, for most where this is triggering though it's a sign that the linter itself is getting stuck running for some reason.

As this particular linter seems to fall into _both_ of the latter categories I'm simply going to provide an option that disables the timeout if the user desires.

**Comment by ryanisnan** [comment] 2016-04-06 18:42
Thanks for the reply @Arcanemagus. I'm interested to see the PR, however, I do not think that the runtime of flake8 is the issue. Given your comments, I think we are solving the wrong problem (at least in my instance, and others in the thread).

I can run flake8 just fine from terminal on the current file I'm working in, which is 1146 lines long, sub 1 second. Saving the file from within Atom triggers the `Process execution timed out` errors.

There very likely is a use-case for linters that *do* take longer and would require the work you're proposing, but I have no reason to suspect that this is the issue being discussed here.

**Comment by ryanisnan** [comment] 2016-04-06 18:44
Also, given that it is happening to some people and not others, it is possibly an environment-specific issue (Atom can't find the linter, permission issue perhaps, etc.). I would love to help debug the issue in any way possible, but am an atom newb.

**Comment by Arcanemagus** [comment] 2016-04-06 19:00
@ryanisnan:

* How long does `flake8` take to run on a file that Atom triggers the error on?
* What OS are you on?
* Do you ever get results? Or do all lints fail?

**Comment by ryanisnan** [comment] 2016-04-06 19:29
@Arcanemagus:

- `flake8` run on files that fail in Atom as expected. I have tested a few files ranging in line count and complexity, and in every case it runs within 1 second.
- Currently on OS X 10.11.4 - also experienced it on 10.11.3
- I never get results from this linter. I do however receive linting from the `linter-pyflakes` linter.

**Comment by Arcanemagus** [comment] 2016-04-06 20:06
Can you try out the latest master, enable the new option, and see if you get any results?

To do that:

```shell
git clone https://github.com/AtomLinter/linter-flake8.git
cd linter-flake8
apm install
apm uninstall linter-flake8
apm link
```
Then restart/reload Atom.

To switch back to the regular version:

```shell
cd linter-flake8
apm unlink
apm install linter-flake8
```

**Comment by ryanisnan** [comment] 2016-04-06 20:58
@Arcanemagus Just tried that. Enabled the new Disable Timeout setting, made some changes that should have caused different flake8 errors, saved the file, waited ~20 seconds, and received no linting.

TIL about `apm`, thanks!

**Comment by ryanisnan** [comment] 2016-04-06 21:09
@Arcanemagus as you may not be able to replicate the issue, let me know if I can help in any way. *ryanisnan* on freenode.

**Comment by Arcanemagus** [comment] 2016-04-21 20:34
@ryanisnan Can you place a breakpoint [here](https://github.com/AtomLinter/linter-flake8/blob/v1.13.0/lib/main.coffee#L207) and see if it is _ever_ returning? :confused:

**Comment by Arcanemagus** [comment] 2016-09-02 21:41
Marking as closed since the initial error would be fixed by the option and there was never a response to the secondary issue.

**Closed by Arcanemagus** 2016-09-02 21:41 UTC

**Comment by v3ss0n** [comment] 2016-09-02 22:05
Confirmed fixed.

**Comment by AjayJohnAlex** [comment] 2018-06-22 12:53
@Arcanemagus 
git clone https://github.com/AtomLinter/linter-flake8.git
cd linter-flake8
apm install
apm uninstall linter-flake8
apm link
i tried this code but im getting 
'apm' is not recognized as an internal or external command,
operable program or batch file.
what should i do ??
