### ISSUE TITLE
linter-flake8 crashes when used with teletype

### ISSUE THREAD

**Issue by richardbann** [AtomLinter/linter-flake8#534] opened 2017-11-22 11:25 UTC
The related issue in the `teletype` repo is here: atom/teletype#228.

**Comment by richardbann** [comment] 2017-11-22 11:28
I think the issue is caused by this line: https://github.com/AtomLinter/linter-flake8/blob/master/lib/main.js#L185

I have changed it to `cwd: '',` and it works well.

My question is: why do we pass the `cwd` to `flake8`? There can be situations, where it is important, I just can not think of any. Maybe checking relative imports or something like that?

Anyway, without it the linter works well (at least to me) with teletype.

Thanks.

**Comment by Arcanemagus** [comment] 2017-11-22 17:18
Closing as a duplicate of https://github.com/atom/teletype/issues/228. It's likely that remote editors will be being blocked at the `linter` level for now.

**Closed by Arcanemagus** 2017-11-22 17:18 UTC

**Comment by Arcanemagus** [comment] 2017-11-22 19:31
It may only be needed for certain edge cases here. There are a few providers that don't need anything other than the file contents in order to return results, but as _most_ of them need some sort of access to the file system the current plan is to simply disable them on remote editors.
