### ISSUE TITLE
Invalid point error

### ISSUE THREAD

**Issue by BryantLuu** [AtomLinter/linter-flake8#265] opened 2016-10-19 02:49 UTC
While I'm writing in python and a function isn't finished like:
```
     def foo()
```
or
```
    if bar:
```

Before I can finish the functions, I'll get the following linter error:

<img width="469" alt="screen shot 2016-10-18 at 7 47 02 pm" src="https://cloud.githubusercontent.com/assets/9938267/19503935/cadd9e98-956b-11e6-8aaf-cb2ca71ce7de.png">

Is this as intended? It keeps happening as I'm writing and it's distracting.

**Comment by mikesdnielsen** [comment] 2016-10-19 14:19
I had this error too and I upgraded my flake8 and it went away, however, it seems like no linting is happing at the moment. 

Atom, version 1.11.2
linter-flake8, version 2.0.2

**Comment by rmari** [comment] 2016-10-19 15:47
Got this too with both Atom v1.10 and v1.11.2, and linter-flake8 v2.02

**Comment by nathancoleman-wf** [comment] 2016-10-19 15:56
Hitting this with:

Atom v1.11.2
linter-flake8 v2.02

**Comment by mikesdnielsen** [comment] 2016-10-19 20:43
Some further investigating here, it seems to likes flake8 version 3.0.3 does fails with an AttributeError on this specific project when I run it from the command line (it's venv). If I downgrade to flake8 2.6.2 (which I have running in another venv), it now works on command line but Atom is still not linting.

**Comment by rexfordadam** [comment] 2016-10-19 23:56
I am also experiencing the same issue on 2 OSX computers (one Sierra, one Yosemite).
Both using: 
Atom v1.11.2
linter-flake8 v2.02

Trying to fix on one resulted in no errors & no linting (linter & flake8 were installed, but did not provide any feedback whatsoever), so I wiped sys & reinstalled and now am back to experiencing the Invalid point error.

In linter-flake8 v2.01 I was receiving the EONet error continuously. Prior to that I have never had any issues.

**Comment by silentsokolov** [comment] 2016-10-20 08:05
Atom v1.10 / linter-flake8 v2.02. It's hell ...

**Comment by mikesdnielsen** [comment] 2016-10-20 10:41
My problem might not have been related to this exactly (although I did see the error in op). 

For me, I got it sorted by updating the package pep8-naming to latest version.

**Comment by yuliji** [comment] 2016-10-21 09:06
I also have this problem.
![linter](https://cloud.githubusercontent.com/assets/1303356/19592938/b02847be-97b0-11e6-808e-f6c21060b66d.png)

**Comment by yuliji** [comment] 2016-10-21 09:55
I think I know the problem in my box.  The flake8 count unicode characters in a different way.  My code contains several unicode lines, and when flake8 reports error, it returns the column number that is much bigger than the actual line length returned by js .length() function.  I guess flake8 count a unicode character as 2 while js count it as 1.

**Comment by nikhilRP** [comment] 2016-10-24 14:47
Anyone found a fix for this, it's very annoying. Thank you so much in advance if one did.

**Comment by Arcanemagus** [comment] 2016-10-24 16:23
@BryantLuu and @rexfordadam Your specific issue is a duplicate of #256, which was reported in [pycqa/flake8#237](https://gitlab.com/pycqa/flake8/issues/237), and fixed in [pycqa/flake8#125](https://gitlab.com/pycqa/flake8/merge_requests/125). Unfortunately I have no idea when this will be fixed in a released version of `flake8`.

@mikesdnielsen `flake8` plugins are _notoriously_ buggy about handling files coming in as `stdin` input, which is how all linting is done using this package in order to support on the fly linting. You might want to [file an issue](https://github.com/PyCQA/pep8-naming/issues/new) over there so it can get fixed.

@yuliji Thank you for being the only person to actually _read_ the message and post the additional details ❤️. I'm guessing your issue is very similar to, if not the same as https://github.com/AtomLinter/linter-flake8/issues/200. Unfortunately I can't find an issue related directly to that over on the `pycodestyle` repo, so you should [file an issue](https://github.com/PyCQA/pycodestyle/issues/new) over there so it can get fixed!.

@rmari, @nathancoleman-wf, @silentsokolov, @nikhilRP as none of you posted any details I can't say for sure what your problem is, this message is a generic "`flake8` returned an invalid point" message, and as you can see above it can have many different causes. That being said it's highly likely you are hitting the same issue @BryantLuu and @rexfordadam are as that is common when editing code.

As the original reported issue here is a duplicate of #256, I'm marking this issue as closed. I'll be posting something in that thread shortly regarding plans to make this much less annoying to the user.

**Closed by Arcanemagus** 2016-10-24 16:23 UTC

**Comment by Arcanemagus** [comment] 2016-11-19 00:07
v2.1.0 has been released which moves the error reporting to a Linter message.

**Comment by BryantLuu** [comment] 2016-11-21 17:02
@Arcanemagus Started messing around after updating. No longer getting those `invalid point encountered!` errors. You are the best!

**Comment by BryantLuu** [comment] 2016-11-21 17:14
@Arcanemagus :( . On:
Atom 1.12.3
flake8: 2.3.0
linter-flake8: 2.1.0

I'm not longer getting the pink pop-ups, so I'm happy :) !
