### ISSUE TITLE
Process exited with non-zero code 1 

### ISSUE THREAD

**Issue by xenithorb** [AtomLinter/linter-flake8#243] opened 2016-09-04 19:50 UTC
```
Error: Process exited with non-zero code: 1
    at ChildProcess.<anonymous> (/home/xenith/git/dotfiles/.atom/packages/linter-flake8/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:51:22)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```
Atom: 1.10.0
Python: Python 3.5.2 :: Anaconda 4.1.1 (64-bit) (also happens with native python or python2)
OS: Fedora 24

**Comment by xenithorb** [comment] 2016-09-04 19:51
```

**Comment by xenithorb** [comment] 2016-09-04 19:58
_sigh_

Strangely I noticed that even after disabling the package it still output the error message - you can see `atom/packages/linter-flake8` in the error, so I know it's coming from that package..... however.....

After I disabled linter-flake8, now I also have the same message from linter-pep8:

```

**Comment by xenithorb** [comment] 2016-09-04 20:18
So far i've tried:

1. using the COPR package'd atom - same result
2. Using the official atom RPM - same result 
3. Not using a symlink for ~/.atom (you'll notice the path is a bit odd) - same result
4. Not using Anaconda python in my $PATH - same result

**Comment by mrx88** [comment] 2016-09-05 07:31
I have exactly the same problem after upgrading linter-flake to latest version (from linter-flake8@1.13.2 to linter-flake8@1.13.3).  I have this problem on Windows and Linux system. I have latest Atom version. Any ideas?

**Comment by mrx88** [comment] 2016-09-05 07:38
FYI: it looks like it's caused by linter-pep8 package upgrade. After rolling back the linter-pep8@1.3.1 version to 1.3.0, error disappeared.

apm install linter-pep8@1.3.0

**Comment by aliva** [comment] 2016-09-06 10:44
I have same issue

```
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

linter@1.11.16
linter-flake8@1.13.3
linter-jscs@4.0.5
linter-jshint@2.1.0
linter-pep8@1.3.1
```

@mrx88 comment fixed the issue.

**Comment by Arcanemagus** [comment] 2016-09-06 22:22
Looks like this was only getting reported here because Atom was loading the `atom-linter` library from this package. The bug in `linter-pep8` has already been fixed in the latest release.

**Closed by Arcanemagus** 2016-09-06 22:22 UTC
