### ISSUE TITLE
Cant take effect when chinese characters are in the text

### ISSUE THREAD

**Issue by CocherZhang** [AtomLinter/linter-flake8#318] opened 2016-12-19 13:27 UTC
As the title. It shows nothing.
And the flake8 can work with the same text.

works
`print("this is a test")`
doesnt work 
`print("这是一个测试")`

After a while, ill test other languages.

**Comment by trifirew** [comment] 2017-01-05 16:37
Same issue.
linter-flake8 does not work with CJK (Chinese, Japanese, and Korean languages) characters, as I've just tested. It does not show any errors or issues when there are CJK characters in the file.

**Comment by Guy-Markman** [comment] 2017-01-14 09:31
Niether Hebrew characters

**Comment by Arcanemagus** [comment] 2017-02-28 18:02
Can you provide more details on your systems? I originally thought this was a duplicate of #282, but I'm actually unable to reproduce this as it works perfectly for me.

**Comment by Arcanemagus** [comment] 2017-02-28 22:05
Actually, turns out that I was still using a test build of `flake8` from the proposed fix for #282... which although these look like different issues might potentially be the same underlying issue.

**Comment by Arcanemagus** [comment] 2017-03-28 05:20
Closing based on the fact that the fixed build of `flake8` wasn't able to reproduce this.

**Closed by Arcanemagus** 2017-03-28 05:20 UTC
Labels: External
