### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by berkaykrc** [AtomLinter/linter-flake8#558] opened 2017-12-21 19:12 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: EOF while scanning triple-quoted string literal`.

Debug information:
Atom version: 1.23.1
Flake8 version: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.3 on Windows`

**Comment by Arcanemagus** [comment] 2017-12-22 17:55
If you are able to provide a file that reproduces this please comment with it over in the following issue, thanks!

**Comment by Arcanemagus** [comment] 2017-12-22 17:55
Duplicate of #505

**Closed by Arcanemagus** 2017-12-22 17:55 UTC
