### ISSUE TITLE
"Error: Flake8 provided an invalid point", when working with cyrillic

### ISSUE THREAD

**Issue by WinaZar** [AtomLinter/linter-flake8#356] opened 2017-02-28 11:13 UTC
Hello! I have an issue when working with cyrillic:

![flake_error](https://cloud.githubusercontent.com/assets/2156116/23402964/e6c10738-fdbe-11e6-88f3-a6c0336dc4f2.png)

If no cyrillic chars, all is normal:

![no_errors](https://cloud.githubusercontent.com/assets/2156116/23402969/eb0f363e-fdbe-11e6-94e9-432ee31c59b8.png)

When running in terminal `flake8 kek.py`  output is normal (`/home/me/kek.py:1:19: E999 SyntaxError: EOL while scanning string literal`) in both cases.

I'm using:
Ubuntu - 16.04
Atom - 1.14.3 x64
linter-flake8 - 2.1.4
flake8 --version: `3.2.1 (pyflakes: 1.2.3, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment] 2017-02-28 18:04
It's _possible_ this is a duplicate of #282 / [pycqa/flake8/#306](https://gitlab.com/pycqa/flake8/issues/306), but as GitHub's images are currently down I'll have to wait to confirm.

**Comment by Arcanemagus** [comment] 2017-02-28 22:04
I'm going to mark this as a duplicate of #318, since the potential fix for that (and #282) seems to be working here as well.

**Closed by Arcanemagus** 2017-02-28 22:04 UTC
