### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by kunalprakash** [AtomLinter/linter-flake8#36] opened 2015-05-17 15:43 UTC
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:810:9)
Package.hasActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:735:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:189:24)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
```

**Comment by ekonstantinidis** [comment] 2015-05-17 20:46
That's the same like #32 . There is a [commit](https://github.com/idan/linter-flake8/commit/53b8d3bbdf98884f9e3be4a6b701eb3d6ee03313) that should be fixing this?

**Comment by badray** [comment] 2015-05-18 18:34
@ekonstantinidis Yep that's right. Closing as duplicate

**Closed by badray** 2015-05-18 18:34 UTC

**Comment by Arcanemagus** [comment] 2016-10-18 18:18
Duplicate of #29 actually.
