### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by DhruvaSambrani** [AtomLinter/linter-flake8#661] opened 2018-11-18 08:39 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: EOF while scanning triple-quoted string literal`.

Debug information:
Atom version: 1.32.2
Flake8 version: `3.6.0 (flake8-docstrings: 1.3.0, pydocstyle: 3.0.0, mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.0 on Windows`

**Comment by Arcanemagus** [comment] 2018-12-17 17:43
Please see the following issue for the information required to see whether this is an issue here in `linter-flake8` (very unlikely), or another bug in `flake8` itself.

**Comment by Arcanemagus** [comment] 2018-12-17 17:43
Duplicate of #505

**Closed by Arcanemagus** 2018-12-17 17:43 UTC
Labels: duplicate
