### ISSUE TITLE
Flake8 rule 'W292' reported an invalid point

### ISSUE THREAD

**Issue by thiagobarbosaal** [AtomLinter/linter-flake8#577] opened 2018-03-14 14:23 UTC
Flake8 reported an invalid point for the rule `W292`, with the messge `no newline at end of file`.

Debug information:
Atom version: 1.24.1
Flake8 version: `3.5.0 (flake8-docstrings: 1.3.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.14 on Windows`

**Comment by Arcanemagus** [comment] 2018-12-17 17:50
Duplicate of #488

**Closed by Arcanemagus** 2018-12-17 17:50 UTC
Labels: duplicate
