### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by egno** [AtomLinter/linter-flake8#492] opened 2017-08-23 04:49 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (97 > 79 characters)`.
That happens when Unicode text is used

Code exampe:
```
    if status:
        result = '%s Мониторинг запущен %s' % (show_emoji(status), result)
    else:
        result = '%s Мониторинг остановлен %s' % (show_emoji(status), result)
```

Debug information:
Atom version: 1.19.2
Flake8 version: `3.3.0 (flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`

**Comment by Arcanemagus** [comment] 2017-08-29 18:14
An issue similar to this has been filed at [pycqa/flake8#366](https://gitlab.com/pycqa/flake8/issues/366). Please follow that issue for updates and if this persists after that is fixed we can file another issue over there to get this resolved.

Marking this as a duplicate of the first report.

**Comment by Arcanemagus** [comment] 2017-08-29 18:14
Duplicate of #486

**Closed by Arcanemagus** 2017-08-29 18:14 UTC
