### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by jmcbruno** [AtomLinter/linter-flake8#551] opened 2017-12-15 14:51 UTC
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

Debug information:
Atom version: 1.23.1
Flake8 version: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.12 on Windows`

**Comment by Arcanemagus** [comment] 2017-12-15 17:35
Duplicate of #466

**Closed by Arcanemagus** 2017-12-15 17:35 UTC
