### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by egno** [AtomLinter/linter-flake8#396] opened 2017-04-18 10:28 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (105 > 79 characters)`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`

**Comment by Arcanemagus** [comment] 2017-04-18 16:01
Closing as a duplicate of #395.

**Closed by Arcanemagus** 2017-04-18 16:01 UTC
