### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by tbenade** [AtomLinter/linter-flake8#317] opened 2016-12-19 01:28 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.1
Flake8 version: `3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 2.7.11 on Darwin`

**Comment by Arcanemagus** [comment] 2016-12-21 22:05
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2016-12-27 17:04
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-27 17:04 UTC
Labels: External
