### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by akabos** [AtomLinter/linter-flake8#408] opened 2017-04-25 05:40 UTC
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

```
'''
Example
'''

class Example:
    example1 = '''
    Example <a href="http://example.com/">
    link on the new line triggers 'invalid points detected'</a>
    need to have line ending with space here to trigger error 
    '''

    example2 = None
```

Debug information:
Atom version: 1.15.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment] 2017-04-25 16:37
Same as with #407, since there were no unicode characters in your example there, I tried to reproduce it and couldn't with both of the following:
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Windows`

Can you upload a zip of the file in question so we can test the _exact_ same content?

**Comment by Arcanemagus** [comment] 2017-05-03 17:42
Closing as I was unable to reproduce this and no example file has been provided.

As this is a `flake8` bug, it will need to be reported in the [`flake8` repository](https://gitlab.com/pycqa/flake8), if you want me to take care of that I'll need a file which lets me reproduce the issue.

**Closed by Arcanemagus** 2017-05-03 17:42 UTC
Labels: External, Unable to reproduce
