### ISSUE TITLE
Error: Process execution timed out

### ISSUE THREAD

**Issue by gjwebber** [AtomLinter/linter-flake8#179] opened 2016-04-06 15:05 UTC
I am sporadically getting the following error:

![image](https://cloud.githubusercontent.com/assets/1949464/14321403/f0a119d8-fc10-11e5-954c-07b3ede65137.png)

My configuration is 100% default, I haven't changed anything at all. It seems I'm not the only one getting it, here is the same issue on Linter-phpcs: https://github.com/AtomLinter/linter-phpcs/issues/114

How long is it expected to take for any problems to be displayed? When it does work, it still doesn't give me instant feedback. It feels like I have to "trigger" a re-check by saving the file, running the code, etc.

**Comment by Arcanemagus** [comment] 2016-04-06 18:08
Duplicate of #169.

**Closed by Arcanemagus** 2016-04-06 18:08 UTC
