### ISSUE TITLE
Cannot get it to work. The flake8 linter does not show anything, no warnings, no errors.

### ISSUE THREAD

**Issue by Chief00** [AtomLinter/linter-flake8#668] opened 2019-01-14 21:34 UTC
I installed Linter-Flake8, after already having linter installed and working, but when typing I get no warnings about the "errors" I'm making. When I use flake8 via PowerShell on the file it shows warnings/errors with my code.

**Comment by Arcanemagus** [comment] 2019-01-14 22:14
See the following issue for more information.

**Comment by Arcanemagus** [comment] 2019-01-14 22:14
Duplicate of #665

**Closed by Arcanemagus** 2019-01-14 22:14 UTC
