### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by dcosmic** [AtomLinter/linter-flake8#655] opened 2018-11-01 16:25 UTC
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ':'`.

Debug information:
Atom version: 1.32.1
Flake8 version: `3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.1 on Windows`

**Comment by Arcanemagus** [comment] 2018-12-17 17:48
Duplicate of #493

**Closed by Arcanemagus** 2018-12-17 17:48 UTC
