### ISSUE TITLE
flake8 raising exceptions in rst file

### ISSUE THREAD

**Issue by Dowwie** [AtomLinter/linter-flake8#139] opened 2016-01-13 00:23 UTC
using Atom ide v1.2.4 , latest version of linter-flake8

flake8 is reading my rst files and alerting me of all kinds of mess 

I don't want linter-flake8 to bother me with rst files.  Is there a way to deactivate this setting?

**Comment by Arcanemagus** [comment] 2016-01-13 00:35
I'm not sure what a "rst" file is, but I'm guessing that _something_ is claiming that `source.python` or `source.python.django` is active at your cursor.

Can you check this by running "Log Cursor Scope" from the command palette?

**Comment by Dowwie** [comment] 2016-01-13 11:53
An "rst" file is one that is written in reStructuredText format.  My rst file features python code blocks.

Here's a scope at cursor dump:

Scopes at Cursor

text.restructuredtext source.gfm.restructuredtext
meta.paragraph.restructuredtext
source.python
meta.function-call.python
meta.function-call.arguments.python
invalid.illegal.operator.python

**Comment by Arcanemagus** [comment] 2016-01-13 17:43
Looks like this is something similar to Markdown, in that this is meant for documentation and not a Python powered templating language, right?

If that is correct the issue is within whichever package you have installed to support reStructuredText: They are marking embedded Python blocks as _full_ Python code (`source.python`) instead of _embedded_ Python (`source.embedded.python`). You should file an issue on the package to have them fix the scope, assuming you are using language-restructuredtext you would do that here: https://github.com/Lukasa/language-restructuredtext/issues

Note this isn't a unique issue, the [language-gfm](https://atom.io/packages/language-gfm) package built into Atom also gets this horribly wrong and causes issues like this all over the linter packages. I'm continuously having to recommend people switch to [language-markdown](https://atom.io/packages/language-markdown).

**Comment by Dowwie** [comment] 2016-01-13 18:18
Yes, this seems to be the case.

**Comment by Arcanemagus** [comment] 2016-01-13 18:21
Marking this as closed then, thanks for reporting this and hopefully they get a fix out for you soon!

If you don't mind when you file an issue reference this one so I can see when that gets fixed in case others are using that package :wink:.

**Closed by Arcanemagus** 2016-01-13 18:21 UTC

**Comment by Dowwie** [comment] 2016-01-13 18:28
just opened a new issue
https://github.com/Lukasa/language-restructuredtext/issues/32
