### ISSUE TITLE
Error: Column start (10) greater than line length (9)?

### ISSUE THREAD

**Issue by GreatWhite181** [AtomLinter/linter-flake8#257] opened 2016-10-17 06:17 UTC
```
Error: Column start (10) greater than line length (9)
    at Object.rangeFromLineNumber (/Users/*me*/.atom/packages/linter-flake8/node_modules/atom-linter/lib/index.js:179:11)
    at extractRange (/Users/*me*/.atom/packages/linter-flake8/lib/main.js:49:18)
    at Object.<anonymous> (/Users/*me*/.atom/packages/linter-flake8/lib/main.js:194:25)
    at undefined.next (native)
    at step (/Users/*me*/.atom/packages/linter-flake8/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Started Getting this error after the latest update. On OSX. Not sure what to do cause I can't really make sense of the error (not that I think i'd be able to fix it myself anyways).

Thanks for your hard work!

**Comment by AntonDnepr** [comment] 2016-10-17 09:25
Have the same on Ubuntu.
It always appears on the defining new function. Sometimes also appears when I type new variables, but not sure if there any dependencies.

**Comment by aramboi** [comment] 2016-10-17 15:44
Similar errors on Ubuntu 16.10 after the last update.

```
Error: Column start (32) greater than line length (31)
Error: Column start (32) greater than line length (31)
    at Object.rangeFromLineNumber (/home/aramboi/.atom/packages/linter-flake8/node_modules/atom-linter/lib/index.js:179:11)
    at extractRange (/home/aramboi/.atom/packages/linter-flake8/lib/main.js:49:18)
    at Object.<anonymous> (/home/aramboi/.atom/packages/linter-flake8/lib/main.js:194:25)
    at undefined.next (native)
    at step (/home/aramboi/.atom/packages/linter-flake8/lib/main.js:9:273)
```

**Comment by aramboi** [comment] 2016-10-17 15:46
Seems to be duplicate of https://github.com/AtomLinter/linter-flake8/issues/256

**Comment by Arcanemagus** [comment] 2016-10-17 16:10
Are you able to post the file that you are seeing this in, in a state where Atom throws that when you open / save it?

@aramboi it's possible, but it's equally likely this is a different issue as that is a generic message thrown when an invalid point is encountered.

**Comment by drafter250** [comment] 2016-10-21 01:55
hitting this on windows to. seems like it happens as I am typing? just a theory but maybe it's on a specifc condition that appears as a flake error while typing.
```
Error: Column start (42) greater than line length (41)
    at Object.rangeFromLineNumber (C:\Users\Bryce\.atom\packages\linter-flake8\node_modules\atom-linter\lib\index.js:179:11)
    at extractRange (C:/Users/Bryce/.atom/packages/linter-flake8/lib/main.js:49:18)
    at Object.<anonymous> (C:/Users/Bryce/.atom/packages/linter-flake8/lib/main.js:194:25)
    at undefined.next (native)
    at step (C:\Users\Bryce\.atom\packages\linter-flake8\lib\main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Arcanemagus** [comment] 2016-10-24 16:28
I'm marking this as closed since it's highly likely this is a duplicate of #256 and @GreatWhite181 hasn't responded with any further details.

@AntonDnepr your issue definitely is a duplicate of #256.

@drafter250 The latest version of `linter-flake8` should be giving you much more detail than that in the console, and a different error message in Atom, please update. It's likely that you are hitting the same issue as #256 though.

**Closed by Arcanemagus** 2016-10-24 16:28 UTC

**Comment by Arcanemagus** [comment] 2016-11-19 00:07
v2.1.0 has been released which moves the error reporting to a Linter message.
