### ISSUE TITLE
linter-flake8 Deprecated: Atom 1.0.3 OS X 10.10.4

### ISSUE THREAD

**Issue by A-M-R** [AtomLinter/linter-flake8#59] opened 2015-07-30 02:26 UTC
<img width="1012" alt="screen shot 2015-07-29 at 10 24 52 pm" src="https://cloud.githubusercontent.com/assets/13447051/8974537/bd16e714-3640-11e5-9881-f973aac6474b.png">

Also deprecated under Atom 1.0.2.

All packages are updated, checked both within Atom and using apm outdated

linter 1.2.4 installed

**Comment by badray** [comment] 2015-07-30 07:26
dupe of #53

**Closed by badray** 2015-07-30 07:26 UTC

**Comment by A-M-R** [comment] 2015-07-30 14:05
@badray The reason I posted was because the references are in different lines of code from the ones that were already open. Is that only based on different operating systems having different packages or is it that Atom's deprecated report just randomly pick lines for that issue report.

Asking so that I know not to post in the future if there is another issue open but with different lines of code shown. I know what a pain duplicate issue reports are and I would rather not add if you don't need the information.

Thank you.

**Comment by Arcanemagus** [comment] 2015-07-30 15:48
Generally with different traces a report is good, in this case though the root cause is all the same: This linter needs to be updated to the new API :stuck_out_tongue:.

There is an implementation waiting for more testing before it can be merged here: https://github.com/AtomLinter/linter-flake8/pull/56.

**Comment by badray** [comment] 2015-08-05 08:30
@A-M-R I know the reason :). I'am on the same page with @Arcanemagus in this case.
