### ISSUE TITLE
flake8 exceptions raising on regular basis when defining docstring

### ISSUE THREAD

**Issue by Dowwie** [AtomLinter/linter-flake8#100] opened 2015-10-19 21:28 UTC
the moment I open a docstring triple quote, I get flake8 exceptions

I'm using the most up to date version of the linter package

**Comment by Arcanemagus** [comment] 2015-10-19 21:39
Does `flake8` work on the command line?

I wouldn't be surprised if you upgraded `pep257` to version 0.7.0. `flake8` crashes with anything newer than 0.6.0 (and older versions to, I think 0.3.0 and below, but I'm not sure.

**Comment by Arcanemagus** [comment] 2015-10-19 21:41
Actually, closing as a duplicate of #96, please respond with what you find there as neither of the other two people reporting this have responded yet.

**Closed by Arcanemagus** 2015-10-19 21:41 UTC

**Comment by Dowwie** [comment] 2015-10-20 18:39
every time I open a docstring I get the flake8 errors on the right of the screen

flake8 DOES work on the command line (using version 2.4.1) 
I'm using python 3.4

![image](https://cloud.githubusercontent.com/assets/2601236/10617334/ec73380e-7737-11e5-9f16-2c56f8d71510.png)
