### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by escalate** [AtomLinter/linter-flake8#312] opened 2016-12-16 06:27 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

#!/usr/bin/env python

Debug information:
Atom version: 1.12.7
Flake8 version: `2.1.0 (pep8: 1.4.6, pyflakes: 0.8.1, mccabe: 0.2.1) CPython 2.7.6 on Linux`

**Comment by Arcanemagus** [comment] 2016-12-21 22:05
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2016-12-27 17:04
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-27 17:04 UTC
Labels: External
