### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by parashkevov** [AtomLinter/linter-flake8#590] opened 2018-04-17 19:23 UTC
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

Debug information:
Atom version: 1.25.0
Flake8 version: `3.2.1 (pyflakes: 1.3.0, mccabe: 0.5.2, pycodestyle: 2.2.0) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment] 2018-12-17 17:47
Duplicate of #493

**Closed by Arcanemagus** 2018-12-17 17:47 UTC
