### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Yvee1** [AtomLinter/linter-flake8#486] opened 2017-08-10 19:14 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (80 > 79 characters)`.

```python
"""Exercise 04 Divisors.

Create a program that asks the user for a number and then prints out a list of
all the divisors of that number. (If you don’t know what a divisor is, it is a
number that divides evenly into another number. For example, 13 is a divisor of
26 because 26 / 13 has no remainder.)

"""
```

Debug information:
Atom version: 1.19.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`

**Comment by Arcanemagus** [comment] 2017-08-29 18:08
Looks like this is being caused by the `’` (in `don’t`) there has been an issue filed similar to this at [pycqa/flake8#366](https://gitlab.com/pycqa/flake8/issues/366). Please follow that issue for updates and if this persists after that is fixed we can file another issue over there to get this resolved.

**Comment by Arcanemagus** [comment] 2017-08-29 18:18
Actually, turns out this is a duplicate of 471.

**Comment by Arcanemagus** [comment] 2017-08-29 18:18
Duplicate of #471

**Closed by Arcanemagus** 2017-08-29 18:18 UTC
Labels: External
