### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by tobymccann** [AtomLinter/linter-flake8#320] opened 2016-12-20 19:16 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

#! /usr/bin/env python3

Debug information:
Atom version: 1.12.7
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment] 2016-12-21 22:07
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2016-12-27 17:05
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-27 17:05 UTC
Labels: External
