### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by jaklsch** [AtomLinter/linter-flake8#429] opened 2017-05-08 07:39 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

import gb_functions

Debug information:
Atom version: 1.16.0
Flake8 version: `2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, ProxyChecker: 0.0.1, hacking.core: 0.0.1, pyflakes: 0.8.1, flake8-docstrings: 1.1.0, pydocstyle: 2.0.0) CPython 3.6.1 on Windows`

**Comment by Arcanemagus** [comment] 2017-05-08 16:41
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-05-12 20:02
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-05-12 20:02 UTC
Labels: External
