### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by woldeaman** [AtomLinter/linter-flake8#296] opened 2016-12-05 13:09 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

Debug information:
Atom version: 1.12.6
Flake8 version: `2.5.1 (pep8: 1.7.0, pyflakes: 1.3.0, mccabe: 0.3.1) CPython 3.5.2 on Darwin`

**Comment by Arcanemagus** [comment] 2016-12-05 21:36
Please update your `flake8` version (`pip install -U flake8`), your version is quite old. This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2016-12-12 19:22
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-12 19:22 UTC
Labels: External
