### ISSUE TITLE
Exception when type quotes.

### ISSUE THREAD

**Issue by pyvim** [AtomLinter/linter-flake8#96] opened 2015-10-15 08:41 UTC
Hello. When I type quotes for docstrings, I get exception.
linter-flake8 1.9.0, linter 1.8.1
flake8 --version
2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 2.7.6 on Linux

![2015-10-15 11 36 40](https://cloud.githubusercontent.com/assets/4338636/10508703/62df29ea-7331-11e5-80ce-0bce42376d7f.png)

**Comment by jeanschmidt** [comment] 2015-10-15 12:04
same here

**Comment by Arcanemagus** [comment] 2015-10-15 16:37
That looks like a `flake8` error from the trace, did you by any chance update `pep257` to 0.7.0? That breaks the docstrings integration.

Does `flake8` work from the command line? Are you using virtualenv and launching Atom from within that virtualenv?

**Comment by Arcanemagus** [comment] 2015-10-19 17:47
@jeanschmidt @pyvim any updates?

**Comment by Arcanemagus** [comment] 2015-10-20 16:28
@Dowwie @jeanschmidt @pyvim I can't reproduce this, so without your input on the cause this won't be fixed...

**Comment by Dowwie** [comment] 2015-10-20 18:40
every time I open a docstring I get the flake8 errors on the right of the screen

flake8 DOES work on the command line (using version 2.4.1) 
I'm using python 3.4

![image](https://cloud.githubusercontent.com/assets/2601236/10617334/ec73380e-7737-11e5-9f16-2c56f8d71510.png)

**Comment by Arcanemagus** [comment] 2015-10-20 19:07
As you can see from your trace, this is an error from `flake8` on your system. It looks like from when it is calling the `pep8` executable, but I'm not positive.

When you try testing `flake8` can you verify that you are calling `/usr/local/bin/flake8` as it appears that is the one that is being called by Atom?

**Comment by jeanschmidt** [comment] 2015-10-20 19:30
Hi!

sorry for not replying it before but I was a bit without time,
I spent some time looking for what is wrong, and it turns out to be exactly what @Arcanemagus said, by just running:
```
$  sudo pip install flake8 --upgrade
Downloading/unpacking flake8 from https://pypi.python.org/packages/py2.py3/f/flake8/flake8-2.4.1-py2.py3-none-any.whl#md5=8767d6cdc4b1654a418f99555c505f84
  Downloading flake8-2.4.1-py2.py3-none-any.whl
Downloading/unpacking mccabe>=0.2.1,<0.4 from https://pypi.python.org/packages/py2.py3/m/mccabe/mccabe-0.3.1-py2.py3-none-any.whl#md5=bea6b1fdd1cffb8afb4d7cac046f104f (from flake8)
  Downloading mccabe-0.3.1-py2.py3-none-any.whl
Requirement already up-to-date: pep8>=1.5.7,!=1.6.0,!=1.6.1,!=1.6.2 in /usr/local/lib/python2.7/dist-packages (from flake8)
Requirement already up-to-date: pyflakes>=0.8.1,<0.9 in /usr/local/lib/python2.7/dist-packages (from flake8)
Installing collected packages: flake8, mccabe
  Found existing installation: flake8 2.2.4
    Uninstalling flake8:
      Successfully uninstalled flake8
  Found existing installation: mccabe 0.2.1
    Uninstalling mccabe:
      Successfully uninstalled mccabe
Successfully installed flake8 mccabe
Cleaning up...
```

all went fine, and now it seems to be fixed, so something was wrong in `flake8`
I was doing a research on flake8 and found this closed issue that may be related: https://gitlab.com/pycqa/flake8/issues/69

thanks you guys for the support!

**Closed** 2015-11-24 18:00 UTC
