### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by MRossol** [AtomLinter/linter-flake8#293] opened 2016-11-30 23:02 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `IndentationError: unindent does not match any outer indentation level`.

Debug information:
Atom version: 1.11.2
Flake8 version: `3.0.4 (mccabe: 0.5.2, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, pycodestyle: 2.0.0, pyflakes: 1.2.3) CPython 3.5.2 on Darwin`

**Comment by Arcanemagus** [comment] 2016-12-01 04:13
Please update your `flake8` version and try again, your issue is likely fixed in v3.2.1 of `flake8`.

**Comment by Arcanemagus** [comment] 2016-12-07 17:08
Closing due to a lack of response, if you are still experiencing issues after updating to `flake8>=3.2.1` (`pip install -U flake8`) please provide an example of code to reproduce this with, thanks!

**Closed by Arcanemagus** 2016-12-07 17:08 UTC
Labels: External
