### ISSUE TITLE
Flake8 rule 'W292' reported an invalid point

### ISSUE THREAD

**Issue by dmort27** [AtomLinter/linter-flake8#431] opened 2017-05-08 14:05 UTC
Flake8 reported an invalid point for the rule `W292`, with the messge `no newline at end of file`.

Debug information:
Atom version: 1.16.0
Flake8 version: `3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.6 on Linux`

**Comment by Arcanemagus** [comment] 2017-05-08 16:39
Closing as a duplicate of #430.

**Closed by Arcanemagus** 2017-05-08 16:39 UTC
Labels: duplicate
