### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by james4388** [AtomLinter/linter-flake8#298] opened 2016-12-07 05:46 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.6
Flake8 version: `3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.12 on Darwin`

**Comment by Arcanemagus** [comment] 2016-12-07 17:07
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.1.0`, while the entire class of `E999` errors should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2016-12-12 19:22
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-12 19:22 UTC
Labels: External

**Comment by Averysaurus** [comment] 2018-09-18 02:32
I'm learning Python using atom and a free textbook. In an exercise, the line:

print("How old are you?", end=' ') 

gave me an E999 - SyntaxError: invalid syntax in flake8. Not sure if I'm in the right place but looking to find out why it's throwing me errors.

**Comment by Arcanemagus** [comment] 2018-09-18 04:46
You're... probably not in the right place. It _sounds_ like you are using `flake8` to lint your code (which is a great start!) and getting a message back from it.

If I had to guess the textbook is written for Python 3, and you are using Python 2.x as changing that from a statement (Python 2) into a function (Python 3) was one of the breaking changes.

I'd recommend looking for a place where they can help you with beginner Python questions, good luck!

**Comment by Averysaurus** [comment] 2018-09-19 16:48
Sorry for crying out in your direction! I was really frustrated. I'm
enamored with Python these days. It's buggy stuff though, it looks like
technical roadblocks are part of the learning process here.

Thank you for responding. I'll look on where to look on for appropriate
support. :)
