### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by SerAlbi** [AtomLinter/linter-flake8#517] opened 2017-10-25 14:25 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: EOL while scanning string literal`.

Debug information:
Atom version: 1.21.1
Flake8 version: `3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.3 on Windows`

**Comment by Arcanemagus** [comment] 2017-12-04 19:52
Duplicate of #505

**Closed by Arcanemagus** 2017-12-04 19:52 UTC

**Comment by SerAlbi** [comment] 2017-12-05 11:16
@Arcanemagus Unfortunately not as the issue dissappeared on it's own..

**Comment by Arcanemagus** [comment] 2017-12-05 17:02
That's unfortunately the nature of most of these: They depend on the _exact_ state of the document when the error was thrown (hence why it's impossible to guess what was triggering this). If you see it again save the file immediately so it can possibly be reproduced 😉.

**Comment by SerAlbi** [comment] 2017-12-07 13:28
@Arcanemagus Sure! 👍
