### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/linter-flake8#409] opened 2017-04-25 09:43 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

```
#!/usr/bin/env python
import os


for var in os.environ:
```

Seems like leaving the `for` without content raises this.

Debug information:
Atom version: 1.16.0
Flake8 version: `2.5.5 (pep8: 1.6.2, pyflakes: 1.2.3, mccabe: 0.2.1) CPython 2.7.13 on Linux`

**Comment by Arcanemagus** [comment] 2017-04-25 16:15
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by brezniczky** [comment] 2017-04-25 17:31
Just as a thought, it might be worth putting some additional message about upgrading in there, around the E901-catching mechanism, to save time & nerves @Arcanemagus :) I actually thought I was being helpful when reporting the bug.

**Comment by Arcanemagus** [comment] 2017-04-25 17:38
The problem with that is that it's a generic "`flake8` gave an invalid point" catch, some "smarts" could be put in there though where if the `flake8` version is below v3.2.1 it tells the user to upgrade first.

**Comment by Arcanemagus** [comment] 2017-05-02 21:27
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-05-02 21:27 UTC
Labels: External
