### ISSUE TITLE
Error message blocks auto-complete suggestion.

### ISSUE THREAD

**Issue by webberwang** [AtomLinter/linter-flake8#489] opened 2017-08-20 07:58 UTC
The error messages block the auto-suggestions. Anyone else experiencing this issue?

![lint-blocking-autocomplete](https://user-images.githubusercontent.com/26264925/29493047-b597eaf8-8542-11e7-85c4-2a3abbf612fb.gif)

**Comment by Arcanemagus** [comment] 2017-08-21 20:48
It's a known issue in `linter-ui-default`, please see the following issue for details and tracking getting it fixed.

**Comment by Arcanemagus** [comment] 2017-08-21 20:48
Duplicate of https://github.com/steelbrain/linter-ui-default/issues/415

**Closed by Arcanemagus** 2017-08-21 20:48 UTC
