### ISSUE TITLE
Flake8 rule 'E261' and 'E202' reported an invalid point

### ISSUE THREAD

**Issue by Mess1an** [AtomLinter/linter-flake8#442] opened 2017-05-16 07:48 UTC
Flake8 reported an invalid point for the rule `E261`, with the messge `at least two spaces before inline comment`.
Flake8 reported an invalid point for the rule `E202`, with the messge `whitespace before ')'`.

from PyQt5.QtWidgets import (QApplication, QPushButton, QVBoxLayout, QGroupBox, QGridLayout, QTextEdit, QRadioButton, QLabel, QMessageBox, QDesktopWidget, qApp, QWidget, QInputDialog)

Debug information:
Atom version: 1.16.0
Flake8 version: `2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, pyflakes: 0.8.1) CPython 3.5.2 on Windows`

**Comment by ddaanet** [comment] 2017-05-17 18:30
Please try again after upgrading flake8.

If the problem is still there: Do you have any unicode characters in your file? There is currently a known bug with how those are handled (pycqa/flake8#306). It's fixed in their master branch and is just waiting on a release.

**Comment by Arcanemagus** [comment] 2017-12-04 20:24
Closing due to a lack of response.

**Closed by Arcanemagus** 2017-12-04 20:24 UTC
