### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Tikani** [AtomLinter/linter-flake8#374] opened 2017-03-22 20:06 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (98 > 79 characters)`.

Debug information:
Atom version: 1.15.0
Flake8 version: `3.3.0 (flake8-docstrings: 1.0.3, pydocstyle: 1.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1rc1 on Windows`

**Comment by Arcanemagus** [comment] 2017-03-22 21:30
Are you able to share code to reproduce this?

There is currently a known bug with unicode characters that _might_ be causing this, but without code it's impossible to say.

**Comment by Tikani** [comment] 2017-03-22 23:22
https://github.com/Tikani/BioStat/blob/master/lab1.py
Atom reported error right at the first line and it's strange because I didn't see such a long string there.

**Comment by Arcanemagus** [comment] 2017-03-22 23:34
Looks like line 37 is the longest line, and it's full of Unicode characters so it's very likely that [pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306) is the problem here. It's been fixed in their `master` branch, so the next release of `flake8` should fix this for you.

The message is only reported on the first line since that is the only line guaranteed to be in the file and we can't use the position from `flake8` since we know that it isn't valid.

**Closed by Arcanemagus** 2017-03-22 23:34 UTC
Labels: External
