### ISSUE TITLE
Unexpected end of file sh: error importing function definition after update to v1.12.1

### ISSUE THREAD

**Issue by msfernandes** [AtomLinter/linter-flake8#165] opened 2016-03-02 14:40 UTC
```
Error: sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
    at parameters.exit (/home/msfernandes/.atom/packages/linter-flake8/node_modules/atom-linter/lib/helpers.js:47:27)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by Arcanemagus** [comment] 2016-03-02 17:20
@steelbrain is this possibly a problem with `consistent-env` pulling in the bash profile?

**Comment by steelbrain** [comment] 2016-03-02 17:21
This is a user misconfiguration, the user has syntax errors in their rc files

**Comment by Arcanemagus** [comment] 2016-09-02 21:38
Closing due to the above comment.

**Closed by Arcanemagus** 2016-09-02 21:38 UTC

**Comment by cnicodeme** [comment] 2016-12-01 16:54
@steelbrain Could you be more precise please? I have the same error as reported and did not touch the rc files manually.

Which rc file are you talking about, and how can I verify that?

**Comment by steelbrain** [comment] 2016-12-01 16:57
@cnicodeme Sure, I was referring to the shell rc files, for example if you use bash it would be `~/.bashrc` or `~/.zshrc` for zsh. To repro the error you can `source ~/path/to/rc/for/your/shell` and see if you get any errors.

**Comment by cnicodeme** [comment] 2016-12-02 13:21
@steelbrain Thank you for your reply. I'm using Bash so I tried source ~/.bashrc and it did not yield anything. I suspect the bash rc file is correct then.

Do you want me to past the detailled log error from Atom?

**Comment by steelbrain** [comment] 2016-12-02 14:37
Yes please, detailed error logs would be helpful

**Comment by cnicodeme** [comment] 2016-12-05 10:08
@steelbrain Here it is : 

```
Error: sh: module: ligne 1: erreur de syntaxe : fin de fichier prématurée sh: erreur lors de l'import de la définition de fonction pour « BASH_FUNC_module » sh: scl: ligne 1: erreur de syntaxe : fin de fichier prématurée sh: erreur lors de l'import de la définition de fonction pour « BASH_FUNC_scl »
Error: sh: module: ligne 1: erreur de syntaxe : fin de fichier prématurée
sh: erreur lors de l'import de la définition de fonction pour « BASH_FUNC_module »
sh: scl: ligne 1: erreur de syntaxe : fin de fichier prématurée
sh: erreur lors de l'import de la définition de fonction pour « BASH_FUNC_scl »
    at ChildProcess.<anonymous> (/home/cnicodeme/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

I'm sorry the output is in French, I hope it won't stop you. If there is something else you need, feel free to ask :)

**Comment by steelbrain** [comment] 2016-12-05 15:48
@cnicodeme while the error is still irrelevant to this package and is a user misconfiguration issue, [a quick google search](https://www.google.com/search?q=error+importing+function+definition+for+%60BASH_FUNC_module%27) lead to me [this solution comment](https://github.com/drush-ops/drush/issues/2065#issuecomment-227820550).

**Comment by cnicodeme** [comment] 2016-12-06 15:55
Thank you @steelbrain. The issue was not solved via your linked solution, but the link right after (https://github.com/AtomLinter/linter-puppet-lint/issues/68).

I did a search before ending here (my search was the reason I come up here ;)), and I decided to ask because I didn't find the right solution for me. In retrospect, I may have searched with the wrong keyword ;)

For all others that have the same issue here, and are **using Fedora**, the solution is simple : 

1. Remove `scl-utils` : `sudo dnf remove scl-utils`. Don't worry, it's not useful on Fedora (it's more RHEL related)
2. Reboot, and you won't have the problem again. **This is important**, if you don't reboot, nothing will change. (Don't ask me why!)

Thank you for your help @steelbrain  :)

**Comment by pferreir** [comment] 2017-01-22 14:33
I'm on Fedora but don't have `scl-utils` installed. I keep seeing this error message all the time.

**Comment by faassen** [comment] 2017-01-28 07:50
I got this message two, but only on one version Fedora 24 and not the other. I removed scl-utils but it had no effect.

But I realized I had flake8 installed in a user-specific bin directory (linking to a virtualenv), and the machine where it worked was using a newer version., and the failing machine had an older version (3.0.x). Once I upgraded to 3.2.1 the problem went away on the machine where it had previously failed.

**Comment by pferreir** [comment] 2017-01-30 07:56
I can confirm that upgrading flake8 works here. Thanks @faassen !

**Comment by Unrud** [comment] 2017-05-17 10:28
> is this possibly a problem with ``consistent-env`` pulling in the bash profile?

``consistent-env`` is causing this problem. It fails if an environment variable contains line breaks.

The original environment contains

  * **BASH_FUNC_scl()**
    ```bash
    () {  local CMD=$1;
     if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
     eval "module $@";
     else
     /usr/bin/scl "$@";
     fi
    }
    ```

but ``consistent-env`` transform it to

  * **BASH_FUNC_scl()**
    ```bash
    () {  local CMD=$1;
    ```
  * **if [ "$CMD"**
    ```
    "load" -o "$CMD" = "unload" ]; then
    ```

**Comment by steelbrain** [comment] 2017-05-17 12:18
Excellent find @Unrud

Could you please post this info on consistent-env repo?

**Comment by fiddybux** [comment] 2017-10-22 09:12
Just as @cnicodeme suggested, I am on Fedora 26 and did:

`sudo dnf remove scl-utils`

Rebooted and errors gone.

I had not touched my .bashrc file...brand new install of Fedora!

**Comment by macm7** [comment] 2018-07-04 08:32
Hey guys i'm having same issue but with drupal any clue what could it be? 
I'm doing a drush cr to clear cache and drop me this errors.
```
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
```

**Comment by j3ffyang** [comment] 2018-08-02 07:24
@cnicodeme - your solution works for me on Fedora 28. Thanks :-)

**Comment by cnicodeme** [comment] 2018-08-02 10:12
Glad I could help ;)
