### ISSUE TITLE
Linter-flake8 makes atom hanging

### ISSUE THREAD

**Issue by dragonxlwang** [AtomLinter/linter-flake8#159] opened 2016-02-21 21:58 UTC
Here's what happens: after starting atom, it just hangs and atom no longer responds. I can produce this problem with only linter package present.

I have tested flake8 alone and it is working. So I assume that the linter-flake8 package makes the atom hangs.

Please let me know if I could help with more details.

Mac OS X El Captain
Atom: 1.5.3
Packages
$ atom_ls_installed_packages
linter@1.11.3
linter-flake8@1.11.0

**Comment by Arcanemagus** [comment] 2016-02-22 19:19
You have some conflicting information there, so I'm going to assume that by "linter package" in the first bit you really meant "linter-flake8".

If you open Atom with no files currently open (no session restored) do you still see this issue?

**Comment by dragonxlwang** [comment] 2016-02-22 19:27
yes, you are right. I mean with only "linter" and "linter-flake8" in package directory.

It only occurs when I open a python file. If no file is open, then it doesn't hang.

**Comment by Arcanemagus** [comment] 2016-02-22 20:42
Well that is interesting... does `apm install linter-flake8@1.10.1` still work?

**Comment by dragonxlwang** [comment] 2016-02-22 20:45
Unfortunately 1.10.1 didn't work either...

![screen shot 2016-02-22 at 2 44 37 pm](https://cloud.githubusercontent.com/assets/15812510/13232018/d42bd286-d972-11e5-9e82-c381b9c4125f.png)

**Comment by Arcanemagus** [comment] 2016-02-22 20:49
Can you try the versions between 1.9.2 and 1.10.1 and see where it breaks?

**Comment by dragonxlwang** [comment] 2016-02-22 20:50
I was just trying exactly what you

**Comment by dragonxlwang** [comment] 2016-02-22 20:51
I was just trying exactly what you are suggesting. It seems only until 1.9.2 works and I am comparing 1.9.2. vs 1.9.3 now.

**Comment by Arcanemagus** [comment] 2016-02-22 20:55
Can you try filling in the name in the `install()` inside `activate()`? (Reverting [this](https://github.com/AtomLinter/linter-flake8/compare/v1.9.2...v1.9.3#diff-2e1bb36917ff76ab7308da52bc968501L136))

**Comment by dragonxlwang** [comment] 2016-02-22 21:00
you mean:

```
138   activate: ->
139     require('atom-package-deps').install('linter-flake8')
```

Still not working...

**Comment by Arcanemagus** [comment] 2016-02-22 21:13
Do you have Node installed? If so could you run `npm install atom-linter@^3.0.0` in the `linter-flake8` directory?

If that doesn't work, try `npm install atom-package-deps@^2.0.5`.

**Comment by Arcanemagus** [comment] 2016-02-22 21:15
If that doesn't make a difference, put a breakpoint [here](https://github.com/AtomLinter/linter-flake8/blob/v1.9.3/lib/main.coffee#L1), and see if it crashes before hitting that. If not, put one [here](https://github.com/AtomLinter/linter-flake8/blob/v1.9.3/lib/main.coffee#L3) and see if it's that first line that is crashing things...

**Comment by dragonxlwang** [comment] 2016-02-22 21:23
I just found after another install of linter-flake8 latest version it simply works. Not sure why.

**Comment by dragonxlwang** [comment] 2016-02-22 21:50
Your method by install node modules of atom-linter works!

Would you please let me know what might be the cause here?

**Comment by dragonxlwang** [comment] 2016-02-22 22:07
I have tried different atom-linter versions and until 4.1.1 it still functions properly. It seems that my problem resulted from atom-linter. What are these packages? Does it work on other's machine?

**Comment by Arcanemagus** [comment] 2016-02-22 23:11
`atom-linter` is a helper module used by almost all of the linters, I might know what's going on here...

**Comment by Arcanemagus** [comment] 2016-02-22 23:12
Does v4.1.1 work and it fails on v4.2.0? Or is v4.1.1 also broken?

**Comment by dragonxlwang** [comment] 2016-02-22 23:13
I also found that my linter-clang didn't work because of the same issue here. seems that there might be some incompatibility (at least on my machine)

none of v4.1.1 or later (including 4.1.1) works.

**Comment by Arcanemagus** [comment] 2016-02-22 23:14
Really? I might expect v4.2.0 to introduce issues, but v4.1.1 should be working...

**Comment by dragonxlwang** [comment] 2016-02-22 23:17
sorry ... I got it wrong. Please ignore my very last reply. 

v4.1.1 works properly.

anything beyond 4.1.1 doesn't work. e.g. v4.2.0

**Comment by Arcanemagus** [comment] 2016-02-22 23:18
So just to be clear, are you saying that:

* v4.1.0 works
* v4.1.1 _doesn't_ work

**Comment by dragonxlwang** [comment] 2016-02-22 23:18
no. 

v4.1.1 works
v4.2.0 doesn't work

**Comment by Arcanemagus** [comment] 2016-02-22 23:19
Okay, that makes some more sense.

**Comment by Arcanemagus** [comment] 2016-02-23 00:18
Btw, a potential fix is incoming in an update to `atom-linter`.

**Comment by dragonxlwang** [comment] 2016-02-23 00:20
if it won't be too much complicated, could you please tell what's the cause of the problem? it seems so far I am the only one experiencing this issue. just curious...

**Comment by Arcanemagus** [comment] 2016-02-23 00:23
You'd have to ask @steelbrain, I'm not entirely sure I understand why this is related to the fix that brings in myself :stuck_out_tongue:.

**Comment by dragonxlwang** [comment] 2016-02-23 00:24
thanks! I might try to reproduce this error to see if it also occurs on my macbook later...

**Comment by steelbrain** [comment] 2016-02-23 00:33
@dragonxlwang The cause of the problem is a deep dependency spawning `bash -ic "env;exit"`, while this works from normally invoked processes, Atom is invoked using `nohup` from it's init script that screws this up. The command above when run in that mode hangs forever and takes 100% cpu usage.

We've worked this around by creating our own package that is more lightweight and reliable

**Comment by dragonxlwang** [comment] 2016-02-23 00:36
thanks @steelbrain 

> We've worked this around by creating our own package that is more lightweight and reliable

So what's the solution? which is the "own package" I should use instead?

**Comment by steelbrain** [comment] 2016-02-23 01:02
@dragonxlwang [`consistent-env`](https://github.com/steelbrain/consistent-env/) is the new package but you won't need to install it manually, it would be included in an update for you as soon as https://github.com/AtomLinter/atom-linter/pull/116 is merged

**Comment by dragonxlwang** [comment] 2016-02-23 01:03
great to know that!

**Comment by dragonxlwang** [comment] 2016-02-28 05:21
Not sure if I am missing anything here, but when today I tried to use 
``
npm install atom-linter@4.1.1
``
It gives me error like this:

``
- xregexp@3.0.0 node_modules/atom-linter/node_modules/xregexp
linter-clang@3.4.4 /Users/xiaolong/.atom/packages/linter-clang
└─┬ atom-linter@4.1.1  invalid
  ├─┬ tmp@0.0.28
  │ └── os-tmpdir@1.0.1
  └── xregexp@3.1.0
``

I have to switch back to 3.0.0 in order to get it work...

**Comment by Arcanemagus** [comment] 2016-03-01 19:32
@dragonxlwang can you run `npm install atom-linter@4.6.1` and try that?

**Comment by dragonxlwang** [comment] 2016-03-01 19:57
@Arcanemagus, I just tried that but it throws error:

```
Error: Unable to determine environment
Error: Unable to determine environment
    at /Users/Foobar/.atom/packages/linter-flake8/node_modules/consistent-env/lib/helpers.js:75:11
```

**Comment by steelbrain** [comment] 2016-03-01 19:58
@dragonxlwang Which shell are you using?

**Comment by dragonxlwang** [comment] 2016-03-01 19:58
zsh

**Comment by steelbrain** [comment] 2016-03-01 19:59
@dragonxlwang Can you try this and see if it works?
```
cd ~/.atom/packages/linter-flake8
npm install consistent-env@latest
```

**Comment by dragonxlwang** [comment] 2016-03-01 20:05
still not working

![screen shot 2016-03-01 at 2 03 19 pm](https://cloud.githubusercontent.com/assets/15812510/13440182/6bb71040-dfb6-11e5-9770-172ad3a76c2e.png)

And I have made sure that consistent-env@latest.

Here's what in the package.json

```
  1 {                                                                                                                                                          [0/9472]
  2   "_args": [
  3     [
  4       "consistent-env@latest",
  5       "/Users/xiaolong/.atom/packages/linter-flake8"
  6     ]
```

**Comment by dragonxlwang** [comment] 2016-03-01 20:13
I think I might know what the problem is. In the helper.js

```
184 function getCommand() {
185   let command = process.env.SHELL;
186   let parameters;
187   let options = { timeout: 3000, encoding: 'utf8' };
188
189   const shell = _path2.default.basename(process.env.SHELL);
190   if (shell === 'bash') {
191     parameters = ['-c', 'source ~/.bashrc;env;exit'];
192   } else if (shell === 'zsh') {
193     parameters = ['-c', ''source ~/.zshrc;env;exit'];
194   }
```

In Ln 193, it tries to source my zshrc which I put some stuff there (specifically, I have a prompt asking whether to login to server/start a tmux etc) which makes helper.js not working correctly. After remove the source command in Ln 193, as:
```
193     parameters = ['-c', ''env;exit'];
```
Everything seems working fine now.

Is there any particular reason to do a source zsh profile here?

**Comment by Arcanemagus** [comment] 2016-03-01 20:16
I believe the purpose of that is to bring in custom paths specified in the user's profile.

**Comment by steelbrain** [comment] 2016-03-01 20:17
@dragonxlwang It's actually a user misconfiguration that you were facing. You should check if stdout is a tty first and then add any prompts, otherwise it can cause a deadlock

**Comment by steelbrain** [comment] 2016-03-01 20:20
Please see this [stackoverflow answer](http://stackoverflow.com/a/911213/2652018)

**Comment by dragonxlwang** [comment] 2016-03-01 20:29
Thanks @steelbrain & @Arcanemagus ! 

I have put a test [[ -t 1 ]] around the prompt function and now everything works!

**Closed** 2016-03-01 20:37 UTC
