### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by mfgabriel92** [AtomLinter/linter-flake8#425] opened 2017-05-02 12:27 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: unexpected EOF while parsing`.

The line `from django.db import models` accused this error.

Debug information:
Atom version: 1.16.0
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.2.1, pyflakes: 1.1.0) CPython 3.5.2 on Linux`

**Comment by Arcanemagus** [comment] 2017-05-02 21:26
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-05-08 16:42
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-05-08 16:42 UTC
Labels: External
