### ISSUE TITLE
Flake8 rule 'W292' reported an invalid point

### ISSUE THREAD

**Issue by chakibBH** [AtomLinter/linter-flake8#506] opened 2017-09-25 10:07 UTC
Flake8 reported an invalid point for the rule `W292`, with the messge `no newline at end of file`.

Debug information:
Atom version: 1.17.2
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment] 2017-12-04 19:59
Duplicate of #488

**Closed by Arcanemagus** 2017-12-04 19:59 UTC
