### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by jacobtobias** [AtomLinter/linter-flake8#441] opened 2017-05-15 22:13 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

```
import mongomock
from data_warehouse.warehouse import MongoDataWarehouse
from data_warehouse.environments.common import case_transformer
db = mongomock.MongoClient().test_db
data_sources = [
    ('patient_fields', JSONDataSource(os.path.join(ENVS_DIR, 'demo/data/patient_fields.json'),
                                      create_details=os.path.join(ENVS_DIR, 'common/data/patient_fields_create_details.json'))),
    ('case_fields', JSONDataSource(os.path.join(ENVS_DIR, 'common/data/case_fields.json'),
                                   create_details=os.path.join(ENVS_DIR, 'common/data/case_fields_create_details.json'))),
    ('sites', JSONDataSource(os.path.join(ENVS_DIR, 'common/data/sites.json'))),
    ('dose_constraints', CSVDataSource(os.path.join(ENVS_DIR, 'common/data/dose_constraints.csv'))),]
data_warehouse = MongoDataWarehouse(
    db,
    sources=[],
    case_transformer=case_transformer.CaseTransformer
)

def test_

```

Debug information:
Atom version: 1.16.0
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 2.7.10 on Darwin`

**Comment by ddaanet** [comment] 2017-05-17 18:25
Duplicate of #433 

@Arcanemagus said: Please update your flake8 version (pip install -U flake8). This particular error should be fixed in flake8>=3.2.1.

**Closed by ddaanet** 2017-05-17 18:25 UTC
