### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by popas90** [AtomLinter/linter-flake8#346] opened 2017-02-10 21:26 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

def run_clustering(path):
    no_nodes, bits, nodes = read_graph(path)
    print(no_nodes, bits, nodes)

Debug information:
Atom version: 1.14.1
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.4.0, pyflakes: 1.0.0) CPython 3.4.3 on Linux`

**Comment by Arcanemagus** [comment] 2017-02-10 22:59
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-02-16 18:17
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-02-16 18:17 UTC
Labels: External
