### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Matt-McConway** [AtomLinter/linter-flake8#471] opened 2017-07-03 07:38 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (80 > 79 characters)`.

Code shown below:
```python
"""
4-2. Animals: Think of at least three different animals that have a common
characteristic. Store the names of these animals in a list, and then use a for
loop to print out the name of each animal.
    • Modify your program to print a statement about each animal, such as
      A dog would make a great pet.

    • Add a line at the end of your program stating what these animals have in
      common  You could print a sentence such as Any of these animals would
      make a great pet!
"""

commonAnimals = ["Dog", "Cat", "Crocodile"]

for animal in commonAnimals:
    print(animal)

print("\n")
# Statement about each animal

for animal in commonAnimals:
    print("A " + animal + "has four legs.")
print("\n")

# Final statement out side of loop
for animal in commonAnimals:
    print("A " + animal + "has four legs.")
print("All of these animals have four legs!")
```

------------------------------------------------------------------------------------------------------

Debug information:
Atom version: 1.18.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.0 on Windows`

**Comment by Matt-McConway** [comment] 2017-07-03 07:39
Thinking it is the bullet points?

**Comment by Arcanemagus** [comment] 2017-07-03 16:10
Hmmm, I can't reproduce this on:
`3.3.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`

Can you upload a zip of the raw file? Maybe something is getting changed in the copy/paste.

**Comment by Matt-McConway** [comment] 2017-07-06 01:33
[ex4-2_pp60_animals.zip](https://github.com/AtomLinter/linter-flake8/files/1126476/ex4-2_pp60_animals.zip)

Here's the zip. 

I get similar problems in some of the other files I am working on (all have the bullet points), but not all of them give the error which is strange.

**Comment by Matt-McConway** [comment] 2017-07-06 19:06
Editing the same file (or any file with the same bullet point character) on my mac system causes flake8 to crash entirely rather than throw the line too long error.

Error log from the console: 
main.js [sm]:201 linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 37: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flake8/checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: unorderable types: str() > int()

**Comment by Arcanemagus** [comment] 2017-07-10 18:50
Can you try updating to Python v3.6.1? That's (supposedly) the only difference in our setups and your example file still works just fine for me.

**Comment by Arcanemagus** [comment] 2017-08-29 18:17
I'm not sure why I couldn't earlier, but I can reproduce this now on `flake8` v3.4.1.

**Comment by Arcanemagus** [comment] 2017-08-29 18:19
@lucasdf Has filed [pycqa/flake8#366](https://gitlab.com/pycqa/flake8/issues/366) to track a similar issue, please follow that for the resolution of this.

**Comment by Arcanemagus** [comment] 2017-12-04 20:03
Currently this is being tracked at https://github.com/PyCQA/pycodestyle/issues/704.

**Comment by Arcanemagus** [comment] 2018-12-17 17:51
Closing as this isn't an issue with `linter-flake8` and there isn't anything we can do here to fix the bug in `flake8`.

**Closed by Arcanemagus** 2018-12-17 17:51 UTC
Labels: External
