### ISSUE TITLE
Failed to spawn flake8

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/linter-flake8#132] opened 2015-12-21 08:39 UTC
Today I started receiving this error when I edit a Python file:

```
Failed to spawn command flake8. Make sure flake8 is installed and on your PATH
Close All
Error: spawn flake8 ENOENT
Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Failed to spawn command flake8. Make sure flake8 is installed and on your PATH
Error: spawn flake8 ENOENT
Error: spawn flake8 ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

That pops up the console, which shows:

![captura de pantalla de 2015-12-21 09-36-06](https://cloud.githubusercontent.com/assets/973709/11926588/50fceb94-a7c6-11e5-9194-a68505727e71.png)

Changing the path of the executable to `/usr/bin/flake8` shows the same error.

```
> which flake8
/usr/bin/flake8
> atom --version
1.3.1
```

I had to disable linter-flake8 for now. :disappointed:

**Comment by Yajo** [comment] 2015-12-21 08:42
Well this was fast to fix. It seems that I was editing a Python file that I had open before I did a `git checkout X` that removed it, so flake8 was trying to process a non-existing file.

Yes it was my fault, but surely catching that exception would benefit.

**Comment by Arcanemagus** [comment] 2015-12-21 18:42
That is just plain _bizarre_, the errors you have up there are saying it couldn't spawn `flake8`, not that `flake8` couldn't find the file once spawned.

You're saying it is working fine for you now one files that exist?

**Comment by Yajo** [comment] 2015-12-22 09:06
So it seems.

**Comment by danielzfranklin** [comment] 2015-12-22 19:42
I have the same error with a python file that does exist, `which flake` gives `/usr/local/bin/flake8`. I have tried restarting Atom.

**Comment by Arcanemagus** [comment] 2015-12-22 19:43
@danielzfranklin are you on OSX? If so you either need to launch Atom from a terminal or specify the full path in the settings.

**Comment by danielzfranklin** [comment] 2015-12-22 19:58
My mistake. It was an issue linter-pep8 not existing caused by your other plugin.

**Comment by Arcanemagus** [comment] 2015-12-28 23:54
Following these steps I am unable to reproduce this:

1. Open a file
2. Make some modifications to the file (do not save)
3. Delete the file from the file manager
4. Make further changes in Atom to the deleted file

That still works fine for me, so for now I'm marking this as closed. If you can figure out steps that work for you @Yajo feel free to reopen this, for now I'm just counting this as a bizarre fluke though.

**Closed by Arcanemagus** 2015-12-28 23:54 UTC

**Comment by Yajo** [comment] 2015-12-29 08:09
OK, I have not been able to reproduce it either.

**Comment by pramaku** [comment] 2017-11-21 16:21
I got the similar error when I installed flake8 package on python virtual env which is is not set in PATH(Windows), adding that directory to the PATH solved the issue.
