### ISSUE TITLE
The linter binary 'flake8' cannot be found.

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/linter-flake8#31] opened 2015-05-06 10:04 UTC
This package gives this error, but if I open a new terminal:

    $ which flake8
    /usr/bin/flake8

**Comment by Yajo** [comment] 2015-05-06 10:05
Versions:

- atom-0.196.0-0.1.fc21.x86_64
- linter-flake8 1.4.0

**Comment by ChaoticMind** [comment] 2015-05-06 13:45
Probably a duplicate of #18

**Comment by badray** [comment] 2015-05-13 09:58
@Yajo Hi, what operating system do you use?

**Comment by Yajo** [comment] 2015-05-13 11:06
Fedora 21. However, I noticed that after updating to atom-0.198.0-0.1.fc21.x86_64 I have not reproduced this bug.

**Comment by badray** [comment] 2015-05-18 18:35
Closed as duplicate of #18

**Closed by badray** 2015-05-18 18:35 UTC
