### ISSUE TITLE
Invalid point encountered!

### ISSUE THREAD

**Issue by theTB** [AtomLinter/linter-flake8#266] opened 2016-10-24 19:23 UTC
I keep getting the following error pop up. Keeps popping up at incomplete lines of code I am still writing. Any suggestions as to what this is?

```
Error: linter-flake8:: Invalid point encountered! See console for details.
Error: linter-flake8:: Invalid point encountered! See console for details.
    at Error (native)
    at extractRange (/Users/tbansil/.atom/packages/linter-flake8/lib/main.js:73:11)
    at Object.<anonymous> (/Users/tbansil/.atom/packages/linter-flake8/lib/main.js:221:25)
    at undefined.next (native)
    at step (/Users/tbansil/.atom/packages/linter-flake8/lib/main.js:9:273)
```

**Comment by Arcanemagus** [comment] 2016-10-24 19:40
If you check the console what is the error code the message was attempting to mark? It's likely this is a duplicate of #256.

**Comment by silentsokolov** [comment] 2016-10-25 12:18
I faced a similar error:

![1477397412157](https://cloud.githubusercontent.com/assets/398939/19685614/2ec1e04a-9ac6-11e6-816d-b9ed5b763af7.jpg)

**Comment by Arcanemagus** [comment] 2016-10-25 16:02
@silentsokolov As I guessed when you posted over in #265, and can now confirm from that screenshot you are _definitely_ hitting the bug in `flake8` that was initially reported in #256.

**Comment by wonderbeyond** [comment] 2016-10-27 06:02
Me too.
![image](https://cloud.githubusercontent.com/assets/228361/19756218/9b6300de-9c4d-11e6-9ab1-12515115c5e8.png)

**Comment by BrunoBernardino** [comment] 2016-10-27 10:03
This is happening very frequently, after the update before the last one, it's tempting me to just disable it :/

**Comment by ashcrow** [comment] 2016-10-27 14:43
I'm having the same issue. I've disabled it for now but am looking forward to re-enabling this plugin. It's extremely helpful!

**Comment by can-z** [comment] 2016-11-02 17:37
My PR #271 seems to at least suppress the errors for now although it might not be accepted as the ultimate fix. You should be able to paste my changes into your local file to fix the issue.

**Closed** 2016-11-18 22:26 UTC
Labels: bug, External

**Comment by Arcanemagus** [comment] 2016-11-19 00:07
v2.1.0 has been released which moves the error reporting to a Linter message.

**Comment by Arcanemagus** [comment] 2016-11-22 18:05
Also it looks like the fix for the originally reported issue has been released in `flake8==3.2.1` 🎉
