### ISSUE TITLE
Improvement: use one python process for flake8

### ISSUE THREAD

**Issue by dessant** [AtomLinter/linter-flake8#118] opened 2015-12-03 12:17 UTC
For every request `flake8.exe` is started and also a new `python` process. Starting a new interpreter every time seems expensive, are there plans to serve linter-flake8 requests from one continuous python process?

https://github.com/sadovnychyi/autocomplete-python does something similar.

**Comment by Arcanemagus** [comment] 2015-12-03 17:11
Duplicate of #117.

**Comment by Arcanemagus** [comment] 2015-12-03 17:12
Thanks for the pointer to an implementation that already has this solved though :wink:.

**Closed by Arcanemagus** 2015-12-03 17:11 UTC
