### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by edcwkim** [AtomLinter/linter-flake8#279] opened 2016-11-19 15:43 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

from django.apps import AppConfig  # This line.

class AuthConfig(AppConfig):
    name = 'snuchoice.auth'
    label = 

Debug information:
Atom version: 1.12.4
Flake8 version: `2.5.4 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 3.4.4 on Windows`

**Comment by Arcanemagus** [comment] 2016-11-20 04:36
Please update your `flake8` version. It looks like you are hitting a bug that has been fixed in v3.1.0.

**Comment by Arcanemagus** [comment] 2016-11-30 17:10
Closing due to a lack of response, if you are still experiencing this after updating to `flake8>=3.2.1` please either file a new issue or respond here with code to reproduce it, thanks!

**Closed by Arcanemagus** 2016-11-30 17:10 UTC
Labels: External
