### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by mr-stateradio** [AtomLinter/linter-flake8#363] opened 2017-03-14 10:35 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.14.1
Flake8 version: `2.4.1 (pep8: 1.5.7, mccabe: 0.3.1, pyflakes: 0.8.1, pep257: 0.2.1.post1) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment] 2017-03-16 20:16
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-03-22 21:30
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-03-22 21:30 UTC
Labels: External
