### ISSUE TITLE
Flake8 rule 'E111' reported an invalid point

### ISSUE THREAD

**Issue by akabos** [AtomLinter/linter-flake8#407] opened 2017-04-25 05:36 UTC
Flake8 reported an invalid point for the rule `E111`, with the messge `indentation is not a multiple of four`.

```

class Example:
    example1 = '''
    Example <a href="http://example.com/">
    link on the new line triggers 'invalid points detected'</a>
    need to have long line here to trigger 'invalid points detected' need to have long line here to trigger 'invalid points detected'
    '''

    example2 = None
```

Debug information:
Atom version: 1.15.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Darwin`

**Comment by Arcanemagus** [comment] 2017-04-25 16:16
There is currently a bug ([pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306)) causing issues with files that have Unicode characters in them. If you don't think this fits your file please upload a sample so we can get this figured out!

**Comment by Arcanemagus** [comment] 2017-04-25 16:34
Since there were no unicode characters in your example there, I tried to reproduce it and couldn't with both of the following:
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.13 on Windows`

Can you upload a zip of the file in question so we can test the _exact_ same content?

**Comment by akabos** [comment] 2017-04-27 05:46
Looks like mixed line endings was a real cause. At least converting file in question to "CR" made this error to disappear. File that displayed this issue contains proprietary source code, so I'm not really able to share it. I'm looking for the way to reproduce the issue though.

**Comment by akabos** [comment] 2017-04-27 05:57
Also had "E902 — TokenError: EOF in multi-line string" in the problematic file. So looks like it was really garbled. 

Bottomline. Converting to CR line endings and resolving E902 fixed  "Flake8 rule 'E111' reported an invalid point" error for me.

**Comment by Arcanemagus** [comment] 2017-04-27 21:47
Hmmm, it's possible this is another problem with the multi-byte character processing bug present in v3.3.0. If you find a minimal  reproduction case that you can share upload it and I'll see if I can reproduce.

**Comment by Arcanemagus** [comment] 2017-05-03 17:40
Closing since I was unable to reproduce and this is a `flake8` bug in the first place. If you can find a file that shows this that you are able to share you can either report this over on the [`flake8` repository](https://gitlab.com/pycqa/flake8), or upload here and I can report it for you.

**Closed by Arcanemagus** 2017-05-03 17:40 UTC
Labels: External, Unable to reproduce
