### ISSUE TITLE
Flake8 rule 'W292' reported an invalid point

### ISSUE THREAD

**Issue by shirshendubhowmick** [AtomLinter/linter-flake8#542] opened 2017-12-04 08:31 UTC
Flake8 reported an invalid point for the rule `W292`, with the messge `no newline at end of file`.

Debug information:
Atom version: 1.22.1
Flake8 version: `3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.2 on Windows`

**Comment by Arcanemagus** [comment] 2017-12-04 20:00
Duplicate of #488

**Closed by Arcanemagus** 2017-12-04 20:00 UTC
