### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by thedreadpirateeric** [AtomLinter/linter-flake8#292] opened 2016-11-29 12:59 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

on line 1:
`from marshmallow import Schema, fields, post_load`

Debug information:
Atom version: 1.12.6
Flake8 version: `3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment] 2016-11-29 17:30
Please update your `flake8`, v3.1.0 fixed one bug related to this, and v3.2.1 fixed a whole class of positioning errors with `E999` messages.

**Comment by Arcanemagus** [comment] 2016-12-07 00:13
Closing due to a lack of response, if you are still experiencing this after updating to `flake8>=3.2.1` please either file a new issue or respond here with code to reproduce it, thanks!

**Closed by Arcanemagus** 2016-12-07 00:13 UTC
Labels: External
