### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by kyrandesa** [AtomLinter/linter-flake8#282] opened 2016-11-21 14:42 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (81 > 79 characters)`.

```py
# -*- coding: utf-8 -*-
```

Debug information:
Atom version: 1.12.5
Flake8 version: `2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, pyflakes: 0.8.1, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1) CPython 3.4.3 on Windows`

**Comment by Arcanemagus** [comment] 2016-11-21 17:20
Interesting, checking if it still does this on current versions of `flake8`.

**Comment by Arcanemagus** [comment] 2016-11-21 18:39
@kyrandesa I'm unable to reproduce this using the above versions on a file containing _just_ the following:

```py
# -*- coding: utf-8 -*-
```

Are you able to share more of the file?
Do you see this with the currently released version of `flake8`? v2.5.5 is no longer supported.

**Comment by kyrandesa** [comment] 2016-11-22 09:02
I updated everything related to flake8 a few times, and the issue still persists. This file doesn't show any other issues than 4x the same Error:
ERROR: Flake8 provided an invalid point! See the trace for details.

Debug information:
Atom version: 1.12.5
Flake8 version: `3.2.1 (hacking.core: 0.0.1, pyflakes: 1.3.0, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, pycodestyle: 2.2.0, ProxyChecker: 0.0.1, mccabe: 0.5.2) CPython 3.4.3 on Windows`

**Comment by kyrandesa** [comment] 2016-11-22 09:11
@Arcanemagus seems I found a minimum file for this: 

```
# -*- coding: utf-8 -*-
"""
Created on 2016-11-18 15:03 CET

@author: xyz
# Send ‘1’ for type E = asset type urn:epc:id:grai:7613264.00381.100000147476
# Send ‘2’ for type B = asset type urn:epc:id:grai:7613264.00307.100000147476
# Send ‘3’ for type C = asset type urn:epc:id:grai:7613264.00308.100000147476
# Send ‘4’ for type U = asset type urn:epc:id:grai:7613264.00319.100000147476
"""
```

When changing the single quotes to straight single quotes, the errors disappear.

**Comment by Arcanemagus** [comment] 2016-11-22 17:57
Thanks, I'll check it out!

**Comment by Arcanemagus** [comment] 2016-11-22 18:20
So far this is almost looking like a bug in how the file contents are being passed to `flake8`, especially since running `flake8` on the file in the CLI doesn't show any issues.

**Comment by Arcanemagus** [comment] 2017-02-15 22:50
Well then, apparently forgetting about this and coming back to it with a fresh perspective was a good thing. It turns out this is a bug in `flake8`, it looks like it's ignoring the `coding` directive for `stdin` input:
![image](https://cloud.githubusercontent.com/assets/427137/22998951/0672073e-f38e-11e6-9d5f-860f7633c124.png)

Looking into whether this is a bug that has already been filed and filing one there if not.

**Comment by Arcanemagus** [comment] 2017-02-15 23:06
Filed https://gitlab.com/pycqa/flake8/issues/306, please follow there for any further information on when this will be fixed.

**Closed by Arcanemagus** 2017-02-15 23:06 UTC
Labels: External
