### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by beterugu** [AtomLinter/linter-flake8#512] opened 2017-10-04 02:40 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (82 > 79 characters)`.

lake8 reported an invalid point for the rule `E501`, with the messge `line too long (82 > 79 characters)`.

Debug information:
Atom version: 1.21.0
Flake8 version: `2.5.5 (pep8: 1.5.7, pyflakes: 0.8.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1) CPython 3.5.2 on Windows`

**Comment by Arcanemagus** [comment] 2017-12-04 20:04
Please follow https://github.com/PyCQA/pycodestyle/issues/704 for updates on when this will get fixed in `pycodestyle` (which `flake8` uses internally).

**Comment by Arcanemagus** [comment] 2017-12-04 20:04
Duplicate of #471

**Closed by Arcanemagus** 2017-12-04 20:04 UTC
