### ISSUE TITLE
Lint files inside of subdirectories of an opened project

### ISSUE THREAD

**Issue by DSamuylov** [AtomLinter/linter-flake8#388] opened 2017-04-07 08:59 UTC
linter-flake8 does not work on files inside of subdirectories of an opened project. For example, I have a project with the following structure:

project
├── package
│   ├── __init__.py
│   ├── core.py
└── script.py

I open project folder in Atom. The linter-flake8 works in `script.py`, however it does not in `core.py`.  Could you reproduce such a problem?

**Comment by lzdych** [comment] 2017-04-11 14:14
I have the same issue - Atom 1.15.0 (OSX), linter 2.1.2, linter-flake8 2.1.5

**Comment by Arcanemagus** [comment] 2017-04-25 16:42
@DSamuylov Using these files I was unable to reproduce your issue: [linter-flake8_GH388.zip](https://github.com/AtomLinter/linter-flake8/files/955817/linter-flake8_GH388.zip)

![image](https://cloud.githubusercontent.com/assets/427137/25396964/69057320-299b-11e7-8730-bd233c25f295.png)

Are you seeing the same with those exact files, or are those also not working for you?

**Comment by DSamuylov** [comment] 2017-04-25 20:51
@Arcanemagus I downloaded the files and the linter does work in your example. However, it still does not work in my project. I am trying to create a minimal example so that you can reproduce the problem. Can be the file size be a reason?

**Comment by DSamuylov** [comment] 2017-04-25 21:01
If I copy the file content from my project to your minimal example it does through warnings/errors, but in my example it still doesn't work... It is very annoying as I cannot see for example what variables are not defined etc. Maybe I enabled some settings (that then should be a project specific)? Do you have any idea what should I check?

**Comment by Arcanemagus** [comment] 2017-04-25 21:29
One of the [flake8 configuration files](https://flake8.readthedocs.io/en/latest/user/configuration.html#configuration-locations) maybe?

**Comment by DSamuylov** [comment] 2017-04-25 21:35
No this I didn't touch. And if I run `flake8 project/project.py` it finds all warnings/errors. But from Atom it does not show anything.

**Comment by Arcanemagus** [comment] 2017-04-25 21:42
Hmmm, can you launch Atom in Developer mode (`atom --dev .`) and see if anything is being written to the console when you lint a file?

**Comment by DSamuylov** [comment] 2017-04-25 21:49
Ok I found out where there is a problem! It does not like that I have a submodule called `project/io.py`. Of course I could rename it, but is it possible to make it in such a way that it does not crash because of that?

The original error message:

    events.js:160 Uncaught Error: write EPIPE
    /Users/denis/.atom/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOM.js:73 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
    /Users/denis/.atom/packages/linter-ui-default/node_modules/fbjs/lib/warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.printWarning @ /Users/denis/.atom/packages/linter-ui-default/node_modules/fbjs/lib/warning.js:36
    3events.js:160 Uncaught Error: write EPIPE
    3/Users/denis/.atom/packages/linter-flake8/lib/main.js:202 flake8 stderr: Traceback (most recent call last):
      File "/Users/denis/anaconda2/bin/flake8", line 7, in <module>
        from flake8.main.cli import main
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/flake8/main/cli.py", line 2, in <module>
        from flake8.main import application
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/flake8/main/application.py", line 9, in <module>
        from flake8 import checker
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/flake8/checker.py", line 17, in <module>
        from flake8 import processor
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/flake8/processor.py", line 3, in <module>
        import io
      File "/Users/denis/Documents/projects/phd/paper-kymo/subreskymo/io.py", line 4, in <module>
        import pandas as pd
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/pandas/__init__.py", line 22, in <module>
        from pandas.compat.numpy import *
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/pandas/compat/__init__.py", line 357, in <module>
        from dateutil import parser as _date_parser
      File "/Users/denis/anaconda2/lib/python2.7/site-packages/dateutil/parser.py", line 37, in <module>
        from io import StringIO
    ImportError: cannot import name StringIO

**Comment by Arcanemagus** [comment] 2017-04-25 22:15
Odd, `flake8` _should_ be crashing in the terminal for you as well then. Also that brings up an excellent point of why that code was even in there, it seems to be hiding many errors from the user...

**Comment by DSamuylov** [comment] 2017-04-26 05:37
Could you now reproduce the issue? Any chance that you can fix it?

**Comment by Arcanemagus** [comment] 2017-04-27 21:59
Hmmm, with an empty `io.py` file in the main project directory `flake8` still runs for me (`pylint` crashes though).

**Comment by Arcanemagus** [comment] 2017-05-03 17:44
Closing as I've been unable to reproduce this and no further information has been provided. If this is still an issue for you please upload a ZIP of a folder structure that reproduces this for you.

**Closed by Arcanemagus** 2017-05-03 17:44 UTC
Labels: Unable to reproduce
