### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by KoushiHarada** [AtomLinter/linter-flake8#331] opened 2017-01-09 07:12 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

Debug information:
Atom version: 1.12.9
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.2.1, pyflakes: 1.1.0) CPython 3.5.2 on Linux`

![screenshot_2017-01-09_16-08-47](https://cloud.githubusercontent.com/assets/10184294/21759265/51f1dd80-d686-11e6-9472-bd0c859f9920.png)

**Comment by Arcanemagus** [comment] 2017-01-09 08:49
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-01-20 17:22
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-01-20 17:22 UTC
Labels: External
