### ISSUE TITLE
Flake8 rule 'W291' reported an invalid point

### ISSUE THREAD

**Issue by tqa236** [AtomLinter/linter-flake8#612] opened 2018-06-12 03:52 UTC
Flake8 reported an invalid point for the rule `W291`, with the messge `trailing whitespace`.

#!/usr/bin/env python

Debug information:
Atom version: 1.26.1
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0, radon: 2.0.2) CPython 2.7.12 on Linux`

**Comment by Arcanemagus** [comment] 2018-12-17 17:45
Duplicate of #628

**Closed by Arcanemagus** 2018-12-17 17:45 UTC
Labels: duplicate
