### ISSUE TITLE
Flake8 rule 'E501' reported an invalid point

### ISSUE THREAD

**Issue by Ars2014** [AtomLinter/linter-flake8#478] opened 2017-07-27 08:13 UTC
Flake8 reported an invalid point for the rule `E501`, with the messge `line too long (101 > 79 characters)`.

`# -*- coding: utf-8; -*-`

Debug information:
Atom version: 1.18.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.5.3 on Windows`

**Comment by Arcanemagus** [comment] 2017-07-31 21:08
Closing as a duplicate of #444.

Unfortunately they _still_ haven't released an updated version of `flake8` that includes the fix, there is nothing that we can do about that here.

**Closed by Arcanemagus** 2017-07-31 21:08 UTC
