### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by gregcowell** [AtomLinter/linter-flake8#364] opened 2017-03-16 01:05 UTC
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: EOL while scanning string literal`.

from flask import Flask, render_template, url_for, request, redirect, session,\
    flash
from flask_script import Manager
from flask_bootstrap import Bootstrap

Debug information:
Atom version: 1.13.1
Flake8 version: `2.5.4 (pep8: 1.7.0, mccabe: 0.2.1, pyflakes: 1.1.0) CPython 3.5.2 on Linux`

**Comment by gregcowell** [comment] 2017-03-16 01:13
There was an error elsewhere in the source file (string literal spanned two lines without continuation character). Flake8 was flagging an error as per initial post for line 1 of the file and was unable to identify the line with the real error.

**Comment by Arcanemagus** [comment] 2017-03-16 20:16
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2017-03-22 21:30
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2017-03-22 21:30 UTC
Labels: External
