### ISSUE TITLE
Flake8 rule 'E999' reported an invalid point

### ISSUE THREAD

**Issue by tsterbak** [AtomLinter/linter-flake8#301] opened 2016-12-08 10:01 UTC
Flake8 reported an invalid point for the rule `E999`, with the messge `SyntaxError: invalid syntax`.

from datetime import datetime, timedelta

Debug information:
Atom version: 1.11.2
Flake8 version: `3.0.4 (pyflakes: 1.2.3, mccabe: 0.5.2, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, pycodestyle: 2.0.0) CPython 3.5.2 on Linux`

**Comment by Arcanemagus** [comment] 2016-12-08 17:41
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

**Comment by Arcanemagus** [comment] 2016-12-14 17:35
Closing due to a lack of response, if you are still having issues after updating `flake8` please provide code to reproduce this!

**Closed by Arcanemagus** 2016-12-14 17:35 UTC
Labels: External
