### ISSUE TITLE
Flake8 rule 'F821' reported an invalid point

### ISSUE THREAD

**Issue by ruichengnew** [AtomLinter/linter-flake8#658] opened 2018-11-09 05:19 UTC
Flake8 reported an invalid point for the rule `F821`, with the messge `undefined name 'e'`.

Debug information:
Atom version: 1.32.1
Flake8 version: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5 on Darwin`

**Comment by Arcanemagus** [comment] 2018-12-17 17:46
Duplicate of #600

**Closed by Arcanemagus** 2018-12-17 17:46 UTC
